### ISSUE TITLE
River of Flame Support

### ISSUE THREAD

**Issue by Warren1001** [bolrog/d2dx#106]
Would it be possible to apply the 60 fps changes to the background of the River of Flame? By the background, I mean the rising and sinking lava "waves" on the boundaries of the map. 60 (or at least higher than current) fps lava would look pretty epic.

**Comment by bolrog** [comment]
The problem with that is that the game does it using tile animation. It just switches between a bunch of images, so it can't be run at a smoother frame rate.

**Comment by bolrog** [comment]
There's nothing that can be done unfortunately (unless someone creates a new tile set). Closing.
