### ISSUE TITLE
Default game size is 640x480, not 800x600

### ISSUE THREAD

**Issue by kangjianbin** [bolrog/d2dx#110]
I set game size to [800,600]. My configuration is:
```
[window]
scale=1			# range 1-3, an integer scale factor for the window
position=[-1, -1]	# if [-1,-1] the window will be centered, otherwise placed at the explicit position given here
frameless=true         # if true, the window frame (caption bar etc) will be removed

[game]
size=[800,600]		# if [-1,-1] d2dx will decide a suitable game size, otherwise will use the size given here
filtering=2             # if 0, will use high quality filtering (sharp, more pixelated)
                        #    1, will use bilinear filtering (blurry)
                        #    2, will use catmull-rom filtering (higher quality than bilinear)
```

However, when I start the game (not the main screen), the default game size is 640x480. I can change it to 800x600 manaully in game.
I tried to set size to [800,601] and [801,600]. I could see the size change to 800x601 and 801x600. Only [800,600] doesn't work.

**Comment by bolrog** [comment]
If you want to play at 800x600, I suggest setting noresmod to true instead.

**Comment by kangjianbin** [comment]
Thanks! After setting it to true, the default resolution is 800x600.
