### ISSUE TITLE
How can I play with 1024x768 resolution on my 1440x900 screen?

### ISSUE THREAD

**Issue by Immersive7** [bolrog/d2dx#111]
I tried to fiddle with the Config txt but there was no effect in any change I did. It's not on read only mode. 

I am using the commands 3dfx -dxnowide 

Is it possible to do it without dropping my native resolution? It would be awesome, thank you.

**Comment by bolrog** [comment]
Did you rename the config file to d2dx.cfg? Then, just set size under the [game] heading:

[game]
size=[1024, 768]

**Comment by Immersive7** [comment]
Oh i missed the rename part! awesome thank you! works like a charm!
