### ISSUE TITLE
Game unable to start

### ISSUE THREAD

**Issue by eskiq** [bolrog/d2dx#112]
It's fresh 1.13c version. While starting a game with -3dfx there is info from D2DX "Please disable compatibility mode". Compatibility mode is off or at least those boxes for them are unchecked. I set nocompatmodefix=true and there is still that info. I'm using Win7 SP1 Ultimate.

**Comment by bolrog** [comment]
Is the name of the cfg file **d2dx.cfg**?

**Comment by eskiq** [comment]
Its the one that come with last D2DX release d2dx-defaults.cfg. I just tried also d2dx.cfg and that one caused fatal error,

**Comment by updawg** [comment]
Eskiq I would ask that you read through the wiki completely before posting
bug reports to rule out user error: https://github.com/bolrog/d2dx/wiki

**Comment by eskiq** [comment]
I have just read installation part and its very sort one and this is exactly what I did.

**Comment by updawg** [comment]
- What I would suggest is to have a clean installation of Diablo 2
   1.13c.
   - Then download the latest release from github.
   - Extract the zip file to your Diablo directory.
   - Copy d2dx-defaults.cfg to a new file named d2dx.cfg.
   - Within d2dx.cfg change nocompatmodefix to true.

**Comment by eskiq** [comment]
That's what I did except part about changing d2dx-defaults.cfg to d2dx.cfg. With d2dx.cfg there is fatal error while with  d2dx-defaults.cfg there is information about compatibility issue. To be sure that I don't messed anything I did fresh installation of 1.13c without any mods.

I do play on single player 1.13c with plugy mod and last Botnet or Battlenet version. To be able to use both versions on the same PC without any addition program I needed to create registry files, 1 for plugy and 1 for botnet. For example this is how it looks for a Battlenet:
launch.cmd:
```
@echo off
C:\Windows\System32\reg.exe import "D:\Games\Diablo II\reg_unplugy.reg"
cmd /c start "" "D:\Games\Diablo II\Game.exe" -3dfx
```
First file is just for loading registry file and launching game.
 reg_unplugy.reg:
  ```
  Windows Registry Editor Version 5.00

    [HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Blizzard Entertainment\Diablo II]
    "GamePath"="D:\Games\Diablo II\Game.exe"
    "InstallPath"="D:\Games\Diablo II\"

    [HKEY_CURRENT_USER\Software\Blizzard Entertainment\Diablo II]
    "Save Path"="D:\Games\Diablo II\Save\"
    "NewSavePath"="D:\Games\Diablo II\Save\"
    "GamePath"="D:\Games\Diablo II\Game.exe"
    "InstallPath"="D:\Games\Diablo II\"
```
It is working perfectly fine with MultiRes mod, but I wanted to replace it with D2DX and see how it works and looks. Depending on the name of the .cfg used by d2dx I do have compatibility info or fatal error. I would like to run 1.13c version with Win XP compatibility as this allows me to bind mouse scroll. The strange thing for me is that, I specially unchecked compatibility mode just for testing purpose and its still showing compatibility info with  d2dx-defaults.cfg or fatal error with d2dx.cfg.

**Comment by bolrog** [comment]
d2dx.cfg is the correct filename, otherwise the file won't be loaded at all.

When you get the fatal error, what does it say exactly?

**Comment by eskiq** [comment]
After starting game screen is frozen and there is no mouse cursor. The only thing I can do at this point is to open Task Manager to kill application "D2DX Fatal Error". With d2dx-defaults.cfg there is just window with information about compatibility mode issue and with d2dx.cfg its fatal error that I can see in task manager. Killing it makes all back to normal.

I replaced now glider to one provided by Sven just to check if game is loading fine and it is starting without any problem.

What is interesting for me is that, with D2DX glider and d2dx-defaults.cfg I do have any window information. I'm writing this only to provide additional information, not that I'm using wrong one after what @updawg wrote.

**Comment by bolrog** [comment]
Hmm. You should be getting a d2dx_log.txt file in the Diablo 2 folder. Could you paste it here?

**Comment by eskiq** [comment]
Yes sure here it is.

```
Game version: 1.0.13.60 (supported)

Apparent Windows version: 6.1 (build 7601).
Actual Windows version: 0.0 (build 0).
Suggesting game size 1366x768.
Writing SGD2FreeRes files.
Initializing SGD2FreeRes.
Fps fix applied.
Menu fps fix applied.
In-game sleep fixes applied.
Using 'Interval1' sync strategy.
Using 'Discard' swap strategy.
d2dx::RenderContext::RenderContext line 183
HRESULT: 0x00000003
Message: The system cannot find the path specified.
```

**Comment by bolrog** [comment]
Thanks! I think you may need this update:

https://support.microsoft.com/en-us/topic/platform-update-for-windows-7-sp1-and-windows-server-2008-r2-sp1-d97da9ca-c15c-b21f-ebb0-838f7be8d9f6

**Comment by eskiq** [comment]
Thank you so much. This solved completely problem and now game is starting perfectly fine.

There are some glitches or black rendering boxes in game that are looking like triangles appearing close to edge of the screen. Its more apparent with perspective mode ON. I also saw them on demonstration [video](https://imgur.com/a/J1F8Ctb). I don't play with perspective mode set to ON and resolution 1366x768 is like cheating so I need to read if I can set lower resolution, but higher than 800x600. My problem with game that is not starting is solved so I'm closing this topic.

**Comment by updawg** [comment]
set a manual resolution of 1024x600 - it will give you true widescreen
without feeling like you are cheating and it will limit the black triangles
along the edges.
