### ISSUE TITLE
ACT4 Pandemonium Fortress roof color error

### ISSUE THREAD

**Issue by HoneSundan** [bolrog/d2dx#113]
roof color keeps changing
The process is slow
Recommended 1.5x speed playback
https://vimeo.com/563560720

**Comment by bolrog** [comment]
It's reported as far back as 2006:
https://www.diabloii.net/forums/threads/anyone-ever-notice-this.522962/

So I think this might be an easter egg in the game.

**Comment by bolrog** [comment]
Closing, since it seems to be part of the game.
