### ISSUE TITLE
 How do I download from here glide3dx.dll ?

### ISSUE THREAD

**Issue by RickyOwens7** [bolrog/d2dx#117]
Hi, I`m new to github. How can I download needed file?

**Comment by iamyoyz** [comment]
you can check the relwase section to download the file

**Comment by Birdsong243** [comment]
Or click here on the right-hand side of the main page:

![image](https://user-images.githubusercontent.com/84301626/123287493-c0f35c00-d4dc-11eb-9e5d-6c5ee24a6acb.png)

**Comment by bolrog** [comment]
Should be solved then.
