### ISSUE TITLE
Can't find the Glide3x.dll file

### ISSUE THREAD

**Issue by famouswolfe** [bolrog/d2dx#120]
Hello, I've reviewed the entire file structure however I cannot locate a file called Glide3x.dll. The only file that came close was located in Src\d2dx and was named glide3x.cpp. 

Edit: it seems like your build failed in GitHub (see attached screenshot below). That might be why there's no dll file.

https://ibb.co/6JDmbzJ

**Comment by jaydee2k** [comment]
Look in the release section. There are prebuild releases...
