### ISSUE TITLE
[Part of the original game] Pandemonium's rainbow roof (Act 4)

### ISSUE THREAD

**Issue by TheLastPlatypus** [bolrog/d2dx#132]
For some reason the game cannot decide which color this roof is supposed to be. It constantly changes when you're standing by, sometimes it's green, sometimes it's purple or red, sometimes it even goes black. I can live with that issue, but had to mention it.

![issue5](https://user-images.githubusercontent.com/89455883/131253482-2721d225-2c39-4941-9b10-790da717f1d5.jpg)
![issue4](https://user-images.githubusercontent.com/89455883/131253490-39cc726d-0ff8-4814-9d22-098e716af69c.jpg)
![issue3](https://user-images.githubusercontent.com/89455883/131253493-3e14b8e1-2fe9-4a25-9e2f-769fbaf0ca08.jpg)
![issue2](https://user-images.githubusercontent.com/89455883/131253498-9b5cb86d-43f4-4101-a627-01287707f084.jpg)
![issue1](https://user-images.githubusercontent.com/89455883/131253501-d8978de5-e781-43d8-8145-18adc919a5ae.jpg)

**Comment by tomasz1986** [comment]
This is a part of the original game 😉 (see https://github.com/bolrog/d2dx/issues/113).

**Comment by TheLastPlatypus** [comment]
Oops. Didn't see that one. Sorry. But the strange thing is that I'm watching videos from other persons on the Internet and it doesn't happen on these videos... BUT ! My guess is that this only happens with glide and not DirectDraw, Direct3D.
