### ISSUE TITLE
High Resolution for 1.14d

### ISSUE THREAD

**Issue by tytannial** [bolrog/d2dx#15]
https://github.com/shalzuth/D2Launcher

**Comment by bolrog** [comment]
Thanks! If I can find all the relevant offsets, I'll try and patch SD-HD to support it.

**Comment by IAmTrial** [comment]
With all due respect for the author of the D2Launcher repo, if you are seeking to integrate the code of that repo into SD-HD, it might not be too useful. [All of D2Launcher's high resolution code is in one file](https://github.com/shalzuth/D2Launcher/blob/master/D2Launcher/MainWindow.cs), and D2Launcher simply replaces 800x600 with another resolution. In its original incarnation, SD-HD used to do something similar, but later progressed into adding resolutions alongside the already existing 640x480 and 800x600. This makes the patches that are applied by the two projects so fundamentally different such that they cannot be useful. SD-HD's final release before being replaced by SGD2FreeRes implements many fancy features that I can already tell are not implemented by D2Launcher.

**Comment by bolrog** [comment]
Yeah I'm more likely to integrate SGD2FreeRes as the built-in solution going forward. But it would be nice to get 1.14d support in there. I might play around with a debugger/cheat engine to look for the proper patch locations.

**Comment by iamyoyz** [comment]
the project SGD2FreeRes now supports 1.14d for your info 😁
