### ISSUE TITLE
Where is the glide3x.dll?

### ISSUE THREAD

**Issue by danteafk** [bolrog/d2dx#157]
Hi and sorry

I've downloaded the zip file d2dx-main.zip but there is no glide3x.dll inside?

**Comment by updawg** [comment]
https://github.com/bolrog/d2dx/releases

download d2dx.zip, you most likely downloaded the source code.

**Comment by danteafk** [comment]
thx

**Comment by oGkspAz** [comment]
Close issue maybe?
