### ISSUE TITLE
V-Sync issue in 0.99.402

### ISSUE THREAD

**Issue by eleriaqueen** [bolrog/d2dx#16]
D2 1.13d, Screen Tearing (which I don't think was there before) appears in 800x600 and Widescreen modes, maybe 640x480 too but I'm not 100% sure. I tested with 60FPS screen mode and 75FPS which my screen supports (and is preferable for D2 since it's 1frame per 3 screen refreshes), and 75fps exhibits tearing even more.

**Comment by bolrog** [comment]
Enabling vsync by default again in the next release.
