### ISSUE TITLE
Fix for blizzard.com "Diablo II is unable to proceed. Unsupported graphics mode."

### ISSUE THREAD

**Issue by 1NSH4N3** [bolrog/d2dx#160]
The game downloaded from blizzard.com it's "1.14B". For the game to work with d2dx you need to patch the game to "1.14D". 
You can do it manually with a patch from the internet or a simpler in-game way.

For the manual version search on the internet for "LODPatch_114d". They are a few places that still have the install file.

Fort the simpler in-game way.
- Enter the game normally.
- Change the "GATEWAY" to "ASIA". (Other regions refuse to download the patch)
- Click the "BATTLE.NET" button. (That will check the game version and download you a patch to 1.14d) 
  (If you get the error "unable to identify the version" check if you did the previous steps)
  (After you patch the game you can change the "GATEWAY" back to your desired region and it will work fine)

This will bring the game to "1.14D" and will work fine with D2DX.

Happy gaming!

**Comment by JourDANGER** [comment]
Here's a link to the patch http://ftp.blizzard.com/pub/diablo2exp/patches/PC/LODPatch_114d.exe
