### ISSUE TITLE
ProjectD2 rathma map will crash

### ISSUE THREAD

**Issue by weili0677** [bolrog/d2dx#168]
I use D2DX play ProjectD2 is very nice.the 60fps is very smooth.
but when I access to the rathma's map,The game will crash.
The error log is:

22:39:36.120  ***** UNHANDLED EXCEPTION: ACCESS_VIOLATION (c0000005)
22:39:36.120  Fault address:  6F858B2B 01:00007B2B D:\Games\Diablo II\ProjectD2\D2Glide.dll
22:39:36.120  eax:24714104 ebx:064fa06e ecx:00000001 edx:00000004 esi:24714104
22:39:36.120  edi:064fa06e ebp:00000004 esp:0019f23c eip:6f858b2b flg:00210212
22:39:36.120  cs:0023 ds:002b es:002b ss:002b fs:0053 gs:002b
22:39:36.120  --------------------------------------
22:39:36.120  Thread 62820 ***

**Comment by skylight102** [comment]
Do you not find that the fps drops to about 25 after 30 mins or so of play? If not, which season are you playing?

Try adding your diablo 2 exe to data execution prevention

**Comment by weili0677** [comment]
Hi, @bolrog ，I find the new issus,the 1068x600 is work fine in singleplayer.  but is not 100% work in multiplayer.
the 856x480 is 100% work fine in singleplayer and multiplayer.
FPS drops issues:
I play in multiplayer start with 1068x600 and  when I change to 856x480,It can success to access the rathma's map(other map is work fine for any resolutions[like 1280x720]),but the FPS is not stable（jump over 10-100FPS）,at last I restart the game with 856x480 the FPS is stable and also can access the rathma's map.

multiplayer crash issues:
If I want access the rathma's map with 1068x600,first I need start game with 856x480 and access to rathma's map,then I restart game into the game and change to 1068x600,finally I maybe have chance(maybe 30%) to access to rathma's map without error.
and if have c0000005 the error log also is:

> 22:39:36.120 ***** UNHANDLED EXCEPTION: ACCESS_VIOLATION (c0000005)
22:39:36.120 Fault address: 6F858B2B 01:00007B2B D:\Games\Diablo II\ProjectD2\D2Glide.dll
22:39:36.120 eax:24714104 ebx:064fa06e ecx:00000001 edx:00000004 esi:24714104
22:39:36.120 edi:064fa06e ebp:00000004 esp:0019f23c eip:6f858b2b flg:00210212
22:39:36.120 cs:0023 ds:002b es:002b ss:002b fs:0053 gs:002b
22:39:36.120 --------------------------------------
22:39:36.120 Thread 62820 ***

**Comment by weili0677** [comment]
> Do you not find that the fps drops to about 25 after 30 mins or so of play? If not, which season are you playing?
> 
> Try adding your diablo 2 exe to data execution prevention

If I no change the resolutions,the FPS is always stable at 60fps.
I play PD2 season 4 patch 8.

**Comment by skylight102** [comment]
That’s interesting as it always reverts to 25 fps after 20 mins of play for me. I’ve tried for weeks to fix. Would it maybe be possible for you to upload a your files so i can check if it fixes the problem for me? Would be really appreciated.

thanks!

**Comment by weili0677** [comment]
> That’s interesting as it always reverts to 25 fps after 20 mins of play for me. I’ve tried for weeks to fix. Would it maybe be possible for you to upload a your files so i can check if it fixes the problem for me? Would be really appreciated.
> 
> thanks!

The Files link:https://github.com/weili0677/BH-CN/blob/main/d2dxTest/d2dx_sgd2freeres.zip
You need set the d2dx_sgd2freeres.dll to ReadOnly.Because I use the newer SGD2Freeres.dll from Github.
And the d2dx.cfg is my config for the D2DX.
The fps and crash issues is in the multiplayer of PD2.If you want to test on my server,you can contact me on Discord,My Discord account is timer#5170

thank you!

**Comment by skylight102** [comment]
Thanks so much Weil, I have tried the files, but for some reason it always gives me CO5 error, I'll contact you on discord. Thanks mate.

**Comment by Fyred** [comment]
> > That’s interesting as it always reverts to 25 fps after 20 mins of play for me. I’ve tried for weeks to fix. Would it maybe be possible for you to upload a your files so i can check if it fixes the problem for me? Would be really appreciated.
> > thanks!
> 
> The Files link:https://github.com/weili0677/BH-CN/blob/main/d2dxTest/d2dx_sgd2freeres.zip You need set the d2dx_sgd2freeres.dll to ReadOnly.Because I use the newer SGD2Freeres.dll from Github. And the d2dx.cfg is my config for the D2DX. The fps and crash issues is in the multiplayer of PD2.If you want to test on my server,you can contact me on Discord,My Discord account is timer#5170
> 
> thank you!

你好，我加你Discord了，求通过。。。

**Comment by weili0677** [comment]
I fix it by myself.Thx.
