### ISSUE TITLE
In game image glitch

### ISSUE THREAD

**Issue by Cristi80** [bolrog/d2dx#171]
It would seem that d2dx supports only 960x540res any higher value causes a image distorsion on the right side of the screen. Im using this with SGD2FreeRes ive followed the instructions closely trying the recommended 1068x600res but i dont manage to get it working. Any help would be appreciated!

![d2dx img glitch](https://user-images.githubusercontent.com/47424326/162860637-5480fce0-44a7-4d3a-86f4-2b78c9477458.png)

**Comment by oGkspAz** [comment]
There must be another cause, Below is mine running at 1068x600 and 1280x720 with no such issue.

![D2_1068x600](https://user-images.githubusercontent.com/13630539/163461903-bde606cc-8702-430e-8ed5-6abbcc6c0a91.jpg)
![D2_1280x720](https://user-images.githubusercontent.com/13630539/163461910-7796775e-a152-46f7-aafa-57a0b13bf462.jpg)

**Comment by Cristi80** [comment]
> There must be another cause, Below is mine running at 1068x600 and 1280x720 with no such issue.

Ive tryed everything i still dont manage to get it working. I was so happy with this mod after all this time i finally get to play D2 at a proper 60fps and decent graphics. I dont like D2R btw i prefer classic :D For the reference im running D2LoD v1.3c, BaseMod and PlugY (all files are in the installation directory). Im not using D2SE Mod Manager and i have the .dlls loaded through BaseMod .ini file as follow:

[ExtraDll1]
Enabled=1
LoadDll1="PlugY.dll" (v14.03)

[ExtraDll2]
Enabled=1
LoadDll3="Glide3x.dll" (d2dx_v0.99.529)

[ExtraDll3]
Enabled=1
LoadDll2="SGD2FreeRes.dll" ( Resolutions present in SGD2FreeResolution.json: "640x480", "800x600", "1068x600", "1280x720")

As stated by the authors the above mods support and D2LoD v1.3c. If im doing something wrong please correct me i really want to get this working.

**Comment by oGkspAz** [comment]
Test without loading sgd2freeres at the same time? I never added both together originally.
Just in case: You will have to copy d2dx-defaults.cfg, rename it to d2dx.cfg, and edit it accordingly instead of freeres' DLL.

**Comment by Cristi80** [comment]
> Test without loading sgd2freeres at the same time? I never added both together originally. Just in case: You will have to copy d2dx-defaults.cfg, rename it to d2dx.cfg, and edit it accordingly instead of freeres' DLL.

Thank you for the reply sir. This is my problem d2dx.cfg i dont know how exactly to edit this file thats why im trying to use SGD2FreeRes. Can you please paste the content of your d2dx.cfg? And if you dont mind explain to me in few steps how do you install it from scratch maybe im doing something wrong.

**Comment by oGkspAz** [comment]
The only line in d2dx.cfg you really need to worry about is:
> size=[1068,600]		# if [-1,-1] d2dx will decide a suitable game size, otherwise will use the size given here

Then your basemod.ini as:
> [ExtraDll1]
> Enabled=1
> LoadDll1="PlugY.dll"
> 
> [ExtraDll2]
> Enabled=0
> LoadDll3=""
> 
> [ExtraDll3]
> Enabled=0
> LoadDll2=""

I tried to load glide3x via basemod but it gave strange behaviour.
Instead, make a shortcut to Diablo II.exe and add -3dfx to the commandline.
Give that a go when you can and report back.

**Comment by Cristi80** [comment]
> I tried to load glide3x via basemod but it gave strange behaviour. Instead, make a shortcut to Diablo II.exe and add -3dfx to the commandline. Give that a go when you can and report back.

Hey there i finally manage to get it working! I must take back the fact that D2DX supports only 960x540res the mod works as intended the problem its on my end. I didnt know how to edit d2dx.cfg ive tried to mix SGD2FreeRes with D2DX and this is where the glitch heppens. I followed what you have told me to use only D2DX and everything works okay now. I even loaded the game through PlugY with no problems. Thank you very mutch for the assistance good sir take care and have a nice day! (After you respond to this i will close issue).

![d2dx img glitch2](https://user-images.githubusercontent.com/47424326/165632625-b77f6a75-ef8b-420d-90ba-99e0d5ecdbfc.png)

**Comment by oGkspAz** [comment]
My pleasure. Likely it was effectively loading two versions of freeres together (or trying to) causing the issue ya. Glad to have helped.
