### ISSUE TITLE
d2dx 1.09d

### ISSUE THREAD

**Issue by Vahsify** [bolrog/d2dx#172]
Hello!

Can you answer whether You will continue to work on the modification? I encountered a problem related to the transition to the next act, when passing the current one (the game is crashing) with the "noresmod=true" (only with "true") and problem with hovering text.

Thank You for Your great work!

**Comment by jaydee2k** [comment]
I tried to update SGD2FreesRes to 3.0.2.1 myself and everything ran through but when loading a char this error message occurs.
![Screenshot 2022-05-20 090009](https://user-images.githubusercontent.com/38560548/169476831-c6387625-532c-4067-83ce-2a9d3d6f0746.png)

**Comment by Marcelo20XX** [comment]
@jaydee2k You will not believe the amount of $h1t I had to digest to fix this issue, from compiling the project myself as debugging, trial and error, etc. But thanks to your detailed comment I have been be able to fix the Act crash on Diablo II LoD 1.09d...

Here is the link to a recompiled dll, just unzip and overwrite whatever file it prompts: [D2DX_1.09d_hotfix](https://drive.google.com/file/d/1Zjk8fQQTMsANLMNBlWFs_ux7C1ykLiBa/view)

I removed the static linking of SGD2FreeRes, so now you need to download and extract the dll and mpq from  "SGD2FreeRes.3.0.2.1.-.Vanilla.zip" on the Diablo II root directory, I tested with that version but in theory it should be compatible with the last release of [Diablo-II-Free-Resolution](https://github.com/mir-diablo-ii-tools/SlashGaming-Diablo-II-Free-Resolution/releases)

https://user-images.githubusercontent.com/15281206/173554018-5098209e-ba3b-4483-8411-fc4258c5af2a.mp4

**Comment by CaptainRay1993** [comment]
> @jaydee2k You will not believe the amount of $h1t I had to digest to fix this issue, from compiling the project myself as debugging, trial and error, etc. But thanks to your detailed comment I have been be able to fix the Act crash on Diablo II LoD 1.09d...
> 
> Here is the link to a recompiled dll, just unzip and overwrite whatever file it prompts: [D2DX_1.09d_hotfix](https://drive.google.com/file/d/1Zjk8fQQTMsANLMNBlWFs_ux7C1ykLiBa/view)
> 
> I removed the static linking of SGD2FreeRes, so now you need to download and extract the dll and mpq from "SGD2FreeRes.3.0.2.1.-.Vanilla.zip" on the Diablo II root directory, I tested with that version but in theory it should be compatible with the last release of [Diablo-II-Free-Resolution](https://github.com/mir-diablo-ii-tools/SlashGaming-Diablo-II-Free-Resolution/releases)
> 
>  2022-06-14.06-14-33.mp4

Hi, I'm quite interested in your fix. Could you tell me which part of the source codes you've changed? Thank you!

**Comment by Marcelo20XX** [comment]
I have updated the diff patch to work against Jarcho's extended_motion fork branch, so you can clone his fork and apply the patch cleanly on it...
[Patch Diff hot fix 1.09d](https://github.com/bolrog/d2dx/files/9651969/My.zip)

**Comment by CaptainRay1993** [comment]
> I have updated the diff patch to work against Jarcho's extended_motion fork branch, so you can clone his fork and apply the patch cleanly on it... [Patch Diff hot fix 1.09d](https://github.com/bolrog/d2dx/files/9651969/My.zip)

Wow! Thank you so much!

**Comment by skylight102** [comment]
Any chance someone could get Jarcho's fork working for 1.13c? Would be more than happy to donate to someone who could help.

Cheers!
