### ISSUE TITLE
854 x 480 resolution support

### ISSUE THREAD

**Issue by daffymahman** [bolrog/d2dx#179]
Would it be possible to add support for 854 x 480 resolution (FWVGA) ? for 3x integer scaling on 2560 x 1440 displays.

Of course you'd still a little bit of overscan but this is a minor issue.

**Comment by OpenRift412** [comment]
that would be nice to have, since it matches the original resolution height but expands it to modern aspect ratios.

**Comment by daffymahman** [comment]
I just realized that you can add custom resolutions in the .ini ... RTFM and all that :)
