### ISSUE TITLE
Unable to run on Linux/Wine

### ISSUE THREAD

**Issue by nesper8** [bolrog/d2dx#193]
D2DX asks for the game to ran without setting compatibility mode and refuses to run through Wine
![Screenshot_20230405_000133](https://user-images.githubusercontent.com/57890520/229995824-93062176-78a8-4ac3-b53c-15d13a2fb701.jpg)
How can i disable this compatibility mode or bypass this message?

**Comment by Kanadeforever** [comment]
Open d2dx.cfg, edit nocompatfx to false, and use Proton-GE to run normally

**Comment by nesper8** [comment]
Thank you. Your solution worked.
I'll close the issue
