### ISSUE TITLE
Fresh install - still no widescreen

### ISSUE THREAD

**Issue by updawg** [bolrog/d2dx#20]
Installed with 1.12a installers, used 1.13c patch, downloaded 0.99.406, extracted to Diablo directory, added -3dfx to parameter lines to shortcut and I do not get HD res. I have a blank option, 640x480 option, and 800x600 option.

Am I doing something wrong?

**Comment by bolrog** [comment]
The "blank" option is the widescreen mode.

**Comment by updawg** [comment]
Not for me. It looks like 640x480 just stretched across the monitor. I've played using the widescreen mod on slash diablo and it is more zoomed out at 1024*600.

**Comment by bolrog** [comment]
Hm, curious. Could you attach a screenshot?

**Comment by updawg** [comment]
[
![Untitled](https://user-images.githubusercontent.com/10038272/113869260-805a3100-977e-11eb-9cad-245ef3436ef4.png)
](url)

**Comment by updawg** [comment]
![Untitled](https://user-images.githubusercontent.com/10038272/113869354-9ff15980-977e-11eb-9e50-6c092ac8a634.png)

**Comment by updawg** [comment]
![Untitled2](https://user-images.githubusercontent.com/10038272/113869633-ee065d00-977e-11eb-8fe0-4f8f34f9572e.png)

**Comment by updawg** [comment]
Here it is at 800x600 - where it is more zoomed out then the HD resolution.

![Untitled3](https://user-images.githubusercontent.com/10038272/113869876-37ef4300-977f-11eb-812b-2a7cde5c52f1.png)

**Comment by bolrog** [comment]
This is widescreen without stretching, although it's vertically slightly less than 600 at 960x540. This resolution was chosen in order to make each pixel 2x2 on a 1920x1080 monitor.

I'm thinking of adding an option to change this default behavior and to allow other resolutions.

**Comment by updawg** [comment]
My monitor resolution is 2560x1440.

**Comment by bolrog** [comment]
Oh I see what you mean now, I didn't look closely enough, sorry. 

Yes I chose the divider 3 for that monitor resolution, so your game is only 853x480. It may be too low.
The next step up is 1280x720, let's try that instead... I'll fix this in the next release, hopefully today.

**Comment by updawg** [comment]
Awesome - thank you so much!

**Comment by updawg** [comment]
This is perfect - thank you so much!

![Untitled4](https://user-images.githubusercontent.com/10038272/113895946-77c22480-9797-11eb-8458-7b9378b0d306.png)
