### ISSUE TITLE
Black And White Cutscenes!

### ISSUE THREAD

**Issue by DanmEr2** [bolrog/d2dx#202]
I tried almost to fix the cutscenes in the game, but nothing helps. Any ideas on how to fix the cutscenes?

**Comment by DanmEr2** [comment]
Here are a couple of examples
![вфвфывфввывыфвфв](https://github.com/bolrog/d2dx/assets/160735290/72a29b0c-f48f-4e03-8f1d-371021d0c343)
![Без имени pnfsds](https://github.com/bolrog/d2dx/assets/160735290/13831e83-f050-4876-9392-22bd94ca407e)

**Comment by DanmEr2** [comment]
Version 1.14d

**Comment by eleriaqueen** [comment]
Don't use base D2DX it's not been update for 3 years. Try this fork https://github.com/Jarcho/d2dx

**Comment by DanmEr2** [comment]
Sorry it still didn't help

**Comment by Jarcho** [comment]
This happens when you use the wrong `binkw32.dll`. Using the bink dll from v1.00-v1.03 with any newer version will cause that effect to happen.

**Comment by DanmEr2** [comment]
Can you post the dll file with which the cutscenes will definitely work?

**Comment by Jarcho** [comment]
The download for [Cactus](https://github.com/fearedbliss/Cactus) includes a full set of dlls for (nearly) every Diablo II version. Just make sure you don't mix versions.

**Comment by DanmEr2** [comment]
Yeah it works thanks
