### ISSUE TITLE
Crash on startup 0.99.406

### ISSUE THREAD

**Issue by IAmTrial** [bolrog/d2dx#21]
D2DX Version: `0.99.406`
OS: Windows 7 Professional, 32-bit
Game Version: Diablo II: Lord of Destruction, version 1.13C

- I am attempting this on a Windows 7 VMWare Guest machine.
- I have tried with and without the command line parameter `-dxnowide`.
- This is a completely vanilla installation.
- I do not have `ddraw.dll` in my Diablo II directory.
  - I do not have CnC-DDraw's `ddraw.dll` in any of the possible search paths.
- The file `glide3x.dll` is in my Diablo II directory and this is the file found in the `0.99.406` release.
- My Diablo II directory is located at `C:\Program Files\Diablo II\Diablo II - LoD\Diablo II - LoD 1.13C D2DX`.

When I run Game.exe with the video mode set to Glide, the game crashes immediately on startup. I have attached a screenshot of the error below.
![D2DX_Crash](https://user-images.githubusercontent.com/26683324/113830671-b32f0580-973b-11eb-922e-e402e7eb486c.png)

**Comment by IAmTrial** [comment]
I would also like to add that I was able to get the game to run, with and without `-dxnowide` under a different VMWare Guest machine:

D2DX Version: `0.99.406`
OS: Windows 10 Pro, 64-bit
Game Version: Diablo II: Lord of Destruction, version 1.13C

**Comment by bolrog** [comment]
Thanks, I'll look into it.

**Comment by bolrog** [comment]
Should hopefully work now in 0.99.408!

**Comment by IAmTrial** [comment]
I attempted to run using `0.99.408` and I appear to be getting a different error, one that gives the game window an unusual shape before crashing. This is the same Windows 7 VMWare Guest machine I described above.
![D2DX_Crash_001](https://user-images.githubusercontent.com/26683324/113958376-d9a17f00-97d5-11eb-8d87-05284db48a5d.png)

**Comment by IAmTrial** [comment]
I would also like to report that with `-dxnowide` enabled, the process is able to start and the window appears to be okay in the main menu. However, after the character is selected and a game is started, immediately on the loading screen, the game window changes to another unusual resolution, but the game does not crash.
![D2DX_Crash_002](https://user-images.githubusercontent.com/26683324/113959029-fb4f3600-97d6-11eb-9e41-4606e320c3a0.png)

**Comment by bolrog** [comment]
That is strange.

You may need to have the DX11 platform update installed: https://support.microsoft.com/en-us/topic/platform-update-for-windows-7-sp1-and-windows-server-2008-r2-sp1-d97da9ca-c15c-b21f-ebb0-838f7be8d9f6

I had this + Win7 SP1 in a VM and was able to run it fine. Let me double check with -dxnowide though.

**Comment by bolrog** [comment]
What is the overall screen size of this VM when it's running btw? I've mainly tested 1920x1080, 1280x720 etc.

**Comment by bolrog** [comment]
This should now be fully fixed!

I've also made it so that D2DX will disable the built-in D2HD if **D2DXGetConfigurator** is called prior to the first Glide function call. Will this work for SGD2FreeRes?

**Comment by IAmTrial** [comment]
Will look into this and update on my findings!

**Comment by IAmTrial** [comment]
I have taken into account the configurator change. SGD2FreeRes works if I have the command line parameters `-dxnowide -dxnoresmod` set. When I remove these command line parameters, the game crashes on startup.

**Comment by bolrog** [comment]
Hmm. I wonder if D2Glide.dll loads the library before you and makes a Glide call. It shouldn't initialize D2HD until that time... unless there is something statically initialized that I'm missing. I'll have a look.

**Comment by updawg** [comment]
I'm running 1.13c with slashdiablos BH.dll. I'm on windows 10 20H2.
Resolution 2560x1440. If you need any more information I can get it later
tonight.

**Comment by bolrog** [comment]
I'll be looking for ways to integrate sgd2fr into D2DX instead of the old D2HD I'm using. Hopefully I can come up with a solution to this at the same time.

I'm not sure whether to use the DLL or whether to statically link + modify it (like with D2HD). I basically just want an in-box solution that works. But perhaps it is cleaner to include the DLL in the release, and set it up with D2DX-preferred defaults if no other mod does...
