### ISSUE TITLE
Crash on Startup 0.99.412

### ISSUE THREAD

**Issue by updawg** [bolrog/d2dx#23]
I was on 408 and it launched perfect. I replaced with 412 and I get the following error.

I'm on Windows 10 with an AMD 3100x and Nvidia 3060TI.
![Screenshot 2021-04-11 200845](https://user-images.githubusercontent.com/10038272/114326216-be01e580-9b01-11eb-9537-f7d317ef24ed.png)

**Comment by updawg** [comment]
If I remove -dxnovsync it launches but window mode is jacked up:

![Screenshot 2021-04-11 201055](https://user-images.githubusercontent.com/10038272/114326271-091bf880-9b02-11eb-88b5-6d8683f4dd54.png)

**Comment by bolrog** [comment]
It seems to be related to running it in Windows XP compatibility mode. I could reproduce this behavior when I enabled that.

It shouldn't be necessary anyway with D2DX, unless some other mod you have needs it. Could you try turning it off?

**Comment by bolrog** [comment]
What version of Windows 10 are you using, do you know?

**Comment by bolrog** [comment]
I've made a fix for the second issue that will go into the next release: D2DX will automatically clear the compatibility mode if necessary.

**Comment by updawg** [comment]
I'm running 1.13c with slashdiablos BH.dll. I'm on windows 10 20H2.
Resolution 2560x1440. If you need any more information I can get it later
tonight.

As for compatibility it could be that is indeed running, I'm not in front of that PC to check. Those are registry settings that don't get changed if you reinstall so it could be from a former mod that I was running - good thinking I'll report back.

**Comment by updawg** [comment]
It works. However, I had to disable compatibility mode on both game.exe and Diablo II.exe, the new checks you added didn't seem to work. Regardless, thank you!
