### ISSUE TITLE
[Minor] Different behavior than LoD for mouse over item

### ISSUE THREAD

**Issue by pairofdocs** [bolrog/d2dx#24]
I noticed that with d2dx, when i place an item into my inventory and do not move my cursor, there is no item stats window displayed.

in LoD (with sven-glide) i see 
![image](https://user-images.githubusercontent.com/76428136/114335147-c5c98600-9b11-11eb-98fa-06876f947f14.png)

but with d2dx, i just see my cursor over the item and no item window
![image](https://user-images.githubusercontent.com/76428136/114336229-1641e300-9b14-11eb-874f-7a579fed9940.png)

I think this started happening after `0.91.328`. It could be related to https://github.com/bolrog/d2dx/blob/main/README.md#091328

**Comment by bolrog** [comment]
Hmm I can't seem to replicate this, when testing. The box shows up for me, even if it sometimes takes a little longer (but less than a second).

**Comment by pairofdocs** [comment]
ahh... 
taking a look

setup:
`d2dx-0.99.412`
`win 10`
`radeon r9 270x`
`D2 LoD 1.13c`
`game.exe -3dfx -w -dxnoaa -dxscale3`

for this test I didn't use Plugy.exe but I saw the same behavior with plugy

![d2dx_wide_item_window](https://user-images.githubusercontent.com/76428136/114422716-626c4200-9b6b-11eb-9b0b-fadf8a1d1072.gif)

maybe it's my previous sven glide settings in the registry that are causing some issues

**Comment by pairofdocs** [comment]
with `d2gx-0.91.327`


![d2dx_wide_item_window_91_327](https://user-images.githubusercontent.com/76428136/114424085-a6137b80-9b6c-11eb-9059-8d9f7a209221.gif)

it's a mystery 🤔

**Comment by bolrog** [comment]
Thanks for all tg details, I do see a noticeable delay until the window pops up here, much longer than it should be. But it does pop up. I'll investigate!

Hm, do you see any blurriness if you just run D2DX in fullscreen btw?

**Comment by pairofdocs** [comment]
No bluriness with d2dx in fullscreen, all crispy and nice

**Comment by bolrog** [comment]
Should be fixed now in release 419.

**Comment by pairofdocs** [comment]
Works! ty!

tested on `d2dx-0.99.419`
