### ISSUE TITLE
FXAA applies on font dc6

### ISSUE THREAD

**Issue by CaiMiao** [bolrog/d2dx#29]
I don't have screenshots atm, but if you need i can provide.

FXAA should not apply on fonts, as this may break some pixel fonts intended display (latin2 or customized one).

If possible, this should be fixed.

**Comment by bolrog** [comment]
Please do, I've tried to not apply it at all on UI elements (text included). So I'd like to fix it.

**Comment by CaiMiao** [comment]
![批注 2021-04-27 235657](https://user-images.githubusercontent.com/4640483/116263636-7d1df800-a7b4-11eb-8deb-9f4ddae949c0.png)

![批注 2021-04-27 235752](https://user-images.githubusercontent.com/4640483/116263655-814a1580-a7b4-11eb-8290-8c8a6841cb1e.png)

notice the properties under the monster hp bar, and first glyph of mana orb text
former is without AA, latter is with AA.

**Comment by bolrog** [comment]
Thanks. A fix is upcoming.

**Comment by bolrog** [comment]
Should be fixed in release 428. Let me know how it looks! (I test only in english)

**Comment by CaiMiao** [comment]
![image](https://user-images.githubusercontent.com/4640483/116406720-eca2ee80-a86b-11eb-907d-a9c01b45f53e.png)
still AA applied.

**Comment by bolrog** [comment]
I'll look into it further. What game version/mods?

**Comment by CaiMiao** [comment]
1.13c, no code edits.

**Comment by bolrog** [comment]
New attempt (release 429), hopefully works now.

**Comment by CaiMiao** [comment]
![image](https://user-images.githubusercontent.com/4640483/116548918-d6f6fd00-a92f-11eb-810e-fa66b7faddbe.png)
sad that still applies....

**Comment by bolrog** [comment]
Ok, it should have been excluded on all text elements. It's clear that I need more material to test with. Not sure if there are language mods for the game or something that I could try...

**Comment by CaiMiao** [comment]
![image](https://user-images.githubusercontent.com/4640483/116801364-43e2e080-ab44-11eb-98aa-01b69d151c30.png)
can confirm latest build looks good to me, ty
