### ISSUE TITLE
How To compile

### ISSUE THREAD

**Issue by Xenthalon** [bolrog/d2dx#30]
Hey, really loving the project!

I'm not fluent with C++ development, but I set up Visual Studio 2019 Community, checked out the repository and added SlashDiablo-HD into the thirdparty folder. But I can't compile the project, it seems the compiler is unhappy with the comments:

`1>Assembling ..\..\thirdparty\SlashDiablo-HD\src\D2HD\D2HDConfigInterception.S...
1>..\..\thirdparty\SlashDiablo-HD\src\D2HD\D2HDConfigInterception.S(1): error A2008: syntax error : /
1>..\..\thirdparty\SlashDiablo-HD\src\D2HD\D2HDConfigInterception.S(2): error A2008: syntax error : *`

Do I have to setup a different linker?

**Comment by bolrog** [comment]
No, but I suspect you're on the wrong branch in the submodule. Make sure SlashDiablo-HD is on the "d2dx_hack" branch.

**Comment by Xenthalon** [comment]
Aha! Thanks a lot, that was it.
