### ISSUE TITLE
crash on switching resolutions

### ISSUE THREAD

**Issue by Yh793** [bolrog/d2dx#31]
D2DX Version: 0.99.429
OS: Windows 7 Professional, 64-bit
Game Version: Diablo II: Lord of Destruction, version 1.13C

hi,bolrog

Thank you for your work.I had trouble switching resolutions in the game.

Multiple tests get error code
1:
halt
location: line #883
expression:unrecoverable internal error 6fe1e203

2:
halt
location: line #904
expression:unrecoverable internal error 6ff6be3c

3:
UNHANDLED EXCEPTION:
ACCESS_VIOLATION (c0000005)

**Comment by Yh793** [comment]
It only occurs when the resolution is switched repeatedly.

**Comment by bolrog** [comment]
Thanks, I'll look into this.

**Comment by bolrog** [comment]
Confirmed, I could reproduce it.

**Comment by IAmTrial** [comment]
This is not a D2DX or D2HD specific bug. You could easily replicate this crash in vanilla Diablo 2 , any version just by spamming the ENTER key when the resolution option is selected.

**Comment by Yh793** [comment]
Yes, I also see a lot of similar errors on search.
