### ISSUE TITLE
Suggestion>No User Window Size Option

### ISSUE THREAD

**Issue by MAXBURAOT** [bolrog/d2dx#35]
-Can u add user window size option in next future release :)
-fps commands are not working also
-better add ini file for easy configuration

**Comment by bolrog** [comment]
Thanks for the suggestions, could you clarify what issues you have with the fps options?

**Comment by MAXBURAOT** [comment]
This one see below pics, so if i type /fps it should show like this :)

![Diablo II 25fps in 3DFX](https://user-images.githubusercontent.com/33173384/116819553-1a0cd680-aba3-11eb-8c8a-a8ce99d7b9c1.png)

**Comment by bolrog** [comment]
I see! I have wondered why the /fps command didn't work, not sure. But I want to add an fps counter and frame time graph eventually.

**Comment by updawg** [comment]
I don't think they have ever worked with glide.

**Comment by bolrog** [comment]
I've added support for a d2dx.cfg file (ini-like format) in release 504.
