### ISSUE TITLE
-dxscale2 not working

### ISSUE THREAD

**Issue by Morrowless** [bolrog/d2dx#39]
With or without plugy 14.02,
I can't get the windowed scaling to work with these params:

Diablo II.exe -3dfx -dxnovsync -dxscale2

Game launches normally and the dx logo is visible so I know it's working. But window scale is 100%.
Monitor is 1440p so it should be be enough for 1600x1200.

I'm using game ver 1.14d, but I'm not using widescreen or anything.

**Comment by bolrog** [comment]
There was a problem that's been fixed in the latest build 503, try it out and see if it helps.

**Comment by Morrowless** [comment]
It's working. Perfect!
