### ISSUE TITLE
Compiling D2DX Windows Build

### ISSUE THREAD

**Issue by MAXBURAOT** [bolrog/d2dx#40]
Hi tried to compile what does the warning means thanks, how to clear it
Attached also when launching the game not working i got error using the current source.

![1](https://user-images.githubusercontent.com/33173384/116888219-c57a6180-ac5d-11eb-8ca6-49f77e59a991.png)
![2](https://user-images.githubusercontent.com/33173384/116888222-c612f800-ac5d-11eb-94f5-bfdd22455070.png)
![Untitled](https://user-images.githubusercontent.com/33173384/116889745-7fbe9880-ac5f-11eb-8b05-7d4b695b8a2f.png)

**Comment by bolrog** [comment]
Which game version?

The warnings are unimportant btw.

**Comment by MAXBURAOT** [comment]
> Which game version?
> 
> The warnings are unimportant btw.

So i did try to compile the current source (clone the rep), file size is different from the one you release v0.99.503, then when i tried to test it doesnt work and show error. 

Diablo II v1.14d
glide3x.dll (v0.99.503) 1.04mb <~Working
glide3x.dll (compiled from git source)  2.60mb <~Error

![zzzz](https://user-images.githubusercontent.com/33173384/117006574-329ffc80-ad1b-11eb-8fd4-7025a9a0984a.png)
![2](https://user-images.githubusercontent.com/33173384/117006576-33d12980-ad1b-11eb-89f7-d30c79513388.png)
![3](https://user-images.githubusercontent.com/33173384/117006578-35025680-ad1b-11eb-8144-db96f0b69710.png)

**Comment by bolrog** [comment]
You are compiling in Debug mode. Switch to Release mode in VS.
