### ISSUE TITLE
1.14d Widescreen support

### ISSUE THREAD

**Issue by iamyoyz** [bolrog/d2dx#51]
![117183607-5130f100-ae0a-11eb-865e-6702d0ff0de5](https://user-images.githubusercontent.com/74028788/117252521-aad00480-ae78-11eb-9b62-c6e9997698a5.jpg)

Hi there
tested this one using SlashGaming-Diablo-II-Free-Resolution and d2dx on 1.14d client  since SlashGaming-Diablo-II-Free-Resolution added support for 1.14d will it be nice to add widescreen support as well?

**Comment by bolrog** [comment]
Yes, I am considering ways to do it. I might integrate SGD2FR, replacing the D2HD I use now.

**Comment by iamyoyz** [comment]
![menu](https://user-images.githubusercontent.com/74028788/117299439-25197c80-aeab-11eb-92ee-fa7de925eb6e.jpg)
is it also possible to remove those black bars in the side ?

**Comment by bolrog** [comment]
The title screen background image is shaped like that (for an old style non-wide display). Unless somebody draws a widescreen version, there's nothing I can do.

**Comment by iamyoyz** [comment]
I remember there was a time in svens glider wrapper when I was on the old laptop that when it is set on full screen it stretch the menu to eliminate the black borders so I thought its on the glider settings but on my new laptop svens glider doesnt work anymore so if its impossible for the d2dx its ok then it was just a suggestion 😁

**Comment by iamyoyz** [comment]
it works now in the latest version 0.99.511 thanks so much!
