### ISSUE TITLE
Feature Request: Project Diablo II Support

### ISSUE THREAD

**Issue by fapmilk** [bolrog/d2dx#53]
Any chance you can make this work with [Project Diablo 2](https://www.projectdiablo2.com/)? I believe it's a 1.13 mod. A modified version of sven's glide wrapper is included with the mod, but replacing it with yours doesn't allow the game to launch. Even basic support (no widescreen, no motion prediction) would be awesome.

**Comment by bolrog** [comment]
Hello,

With release 507 you should be able to try it with PD2. However you have to delete the D2HD.DLL that is included with PD2, in addition to copying D2DX into the folder. (D2DX contains its own version of D2HD)

I've only tried it in single player a little with PD2, and that worked for me, but I haven't connected to their server etc. Do be careful so you don't break any policy they might have, especially with motion prediction on.

**Comment by fapmilk** [comment]
It works great! Thank you.
