### ISSUE TITLE
Feature Request: Custom Resolutions

### ISSUE THREAD

**Issue by fapmilk** [bolrog/d2dx#55]
I generally prefer playing D2 at 800x600 internal because that's what the game was last designed for.  And we all know that many gameplay elements break or become trivialized not far beyond this play area. However I've recently been messing with other resolutions and noticed that D2DX's internal resolution choices really don't make sense to me, from a gameplay perspective, at some resolutions. Specifically 1920x1080. Which according to steam is still by far the most common resolution with 67% of users.

It doesn't make sense to me that you get significantly more screen space with many lower resolutions than you do with higher ones. See screenshots below.

[1280x720](https://i.imgur.com/P3XesOq.jpg)
[1366x768](https://i.imgur.com/21nUvRh.jpg)
[1600x900](https://i.imgur.com/hZLjPu3.jpg)
[1920x1080](https://i.imgur.com/5PEUY6t.jpg)

In fact, with the default scaling at 1920x1080 you actually LOSE screen space when using -nowide. Not only do you lose both horizontal and vertical space but you also lose the skill + stat buttons. See below.

[1920x1080 (800x600)](https://i.imgur.com/GwlcoJX.jpg) = -dxnowide -dxnoresmod
[1920x1080 (720x540)](https://i.imgur.com/gaGCrrZ.jpg) = -dxnowide

I understand that your goal is to keep D2DX as simple as possible so it "just works" with no configuration. I partially agree with that philosophy and think that it's great for defaults to work perfectly for the majority of cases. But I've always believed that when it comes to game options, having more choice and control is always better than less. Even if they're only accessible via external config files.

Correct me if I'm wrong but there isn't currently a way to choose the desired internal resolution besides the in game option. I would like to be able to choose the exact resolution for the game to run at via command line / config file even if it's not ideal visually because of scaling.

**Comment by bolrog** [comment]
Thanks for your thoughts. I am considering a good approach for this, as others have wished for changes as well.

The reason for the current in-game resolution choices have to do with integer scaling etc. I go into the reasoning behind the choices here: https://github.com/bolrog/d2dx/wiki/In-game-Resolutions

I think I'll open up custom sizing though. Maybe that's a good start.

**Comment by Yh793** [comment]
> I just published release 510, you can now set a custom game size in d2dx.cfg (see the wiki for how).
`[game]
size=[800,600]`
this setting,crash in game click video option.
1280x720, 640x480, 700x525, 1024x768 pass the test.

**Comment by fapmilk** [comment]
It works great! Thank you for implementing this so quickly.

> The reason for the current in-game resolution choices have to do with integer scaling etc. I go into the reasoning behind the choices here: https://github.com/bolrog/d2dx/wiki/In-game-Resolutions

I definitely agree that integer scaling is ideal. But I appreciate having the choice between pixel perfect graphics and more screen space. Being able to play at 1064x600, which fills 1920x1080 without "losing" play area vs 800x600, with all the other features D2DX offers is outstanding. Though I must admit that, after messing with various resolutions, I'm starting to lean towards your original integer scaling choice of 960x540 for 1920x1080. While you lose a little vertical space you gain horizontal and the pixel perfect graphics really are the way the game was made to be experienced. I do really appreciate you adding the option though. I can see this being useful at certain resolutions like 2560x1440. 1280x720 is too large of play area in my opinion. But now you could choose something like 1000x700 x2 scale windowed which would fill a good amount of the screen while keeping the game area a lot closer to the original.

I wonder, would it be possible to implement an option for windowed mode-like scaling factors (1,2,3) in fullscreen with black bars on all sides? So the game would be centered and the empty area would be letterboxed / pillarboxed. This could be useful at certain resolutions like with the 2560x1440 example I mentioned above.

> I'm slightly wary about issues that might arise when pushing the game too far resolution-wise though.

I agree. I played around with a bunch of resolutions and anything beyond about 1000x700 is honestly too much. I didn't notice any issues that seemed related to D2DX even at 1600x900 (which is way too large). However, the game engine visual "bugs" start becoming quite apparent at the corners of the screen beyond about 1000x700. Such as objects like trees disappearing, light sources like torches turning off, and empty black terrain. Not to mention the UI gets smaller as you increase resolution, which isn't ideal.

**Comment by iamyoyz** [comment]
wanted to run 1024x 600 on my screen I did set it on the game resolution but when I launch the game it still on 800x600

**Comment by Yh793** [comment]
> wanted to run 1024x 600 on my screen I did set it on the game resolution but when I launch the game it still on 800x600

The set resolution will not take effect until it enters the game.

**Comment by iamyoyz** [comment]
confirmed it works even the cinematics I've encountered(not full screen) also fixed the issue.. Thanks @bolrog
