### ISSUE TITLE
Some Errors and Suggestion v0.99.510

### ISSUE THREAD

**Issue by MAXBURAOT** [bolrog/d2dx#57]
Suggestion:
-I hope in the future version could show the video resolution size  :)
-in D2DX.cfg can we set multiple custom screen size
-fps commands etc

```
"Ingame Resolutions": [
            "1024x720",
            "1280x720",
            "1360x720"
             ETC
```
![111](https://user-images.githubusercontent.com/33173384/117675279-01be3c80-b1df-11eb-9cb3-af3453f1e9ec.png)

I encountered this small error running with SlashGaming dlls normally i run the .bat inside the C:\Diablo II\SlashGaming Fixes 2021\SGGL - Diablo II  Non DKL 3DFX.bat

C:\Diablo II\SlashGaming Fixes 2021\Glide3x.dll (D2DX) <~ With Glide3x.dll no errors
C:\Diablo II\SlashGaming Fixes 2021\   <~Without Glide3x.dll got errors

Another test i did, run C:\Diablo II\SlashGaming Fixes 2021\SGGL - Diablo II  Non DKL 3DFX.bat, Glide3x.dll is inside Diablo II Root folder Got Errors
C:\Diablo II\Glide3x.dll (D2DX)

run C:\Diablo II\SlashGaming Fixes 2021\SGGL - Diablo II  Non DKL 3DFX.bat, Glide3x.dll is inside Diablo II Root folder No Errors and game launching (not present inside the C:\Diablo II\SlashGaming Fixes 2021\  folder)
C:\Diablo II\Glide3x.dll (nGkide)
C:\Diablo II\Glide3x.dll (dGVoodoo)

```
SGGL - Diablo II  Non DKL 3DFX.bat config
@echo off

set "CURRENT=%~dp0"

START "" "%CURRENT%SGGL.exe" ^
    	-g "../Game.exe" ^
    	-a "-w -3dfx" ^
	-n 1 ^
	-l "%CURRENT%SGD2FreeDeMin.dll" ^
	-l "%CURRENT%SGD2FreeDisplayFix.dll" ^
	-l "%CURRENT%SGD2FreeMultibox.dll" ^
	-l "%CURRENT%SGD2FreeRes.dll" ^
	-l "%CURRENT%SGD2TrueVersionLabel.dll" ^
```

![222](https://user-images.githubusercontent.com/33173384/117675927-a17bca80-b1df-11eb-8df2-9ce4ff064e72.png)
![333](https://user-images.githubusercontent.com/33173384/117675942-a5a7e800-b1df-11eb-9e97-5360fede70cd.png)

**Comment by bolrog** [comment]
I'm planning on using sgd2fr instead of D2HD as the built-in resolution mod, hopefully I can get started on that soon. It should solve some of the issues you mention.

Regarding the third issue I think you're using an older version of sgd2fr that didn't support D2DX directly. The new one should.

**Comment by bolrog** [comment]
SGD2FreeRes will be the built-in res mod in release 511, which might be published when you read this.

**Comment by MAXBURAOT** [comment]
thanks for the big update, just now i test the new v0.99.512b, i encountered this issues
-AV detecting glide3x.dll as a virus (maybe signature)
-Cannot set custom Ingame Resolutions in D2DX_SGD2FreeRes.json, when setting in D2DX.cfg is size=[-1,-1]
-in D2DX.cfg if i set the size=[1280,720], and if i tried to change to other display mode its crashing
-Setting in D2DX_SGD2FreeRes.json are not saving can use only 3 modes of display

Using:
Win10x64
Diablo II LOD v1.13d

```
My D2DX_SGD2FreeRes.json Config
{
    "SlashGaming Diablo II Free Resolution": {
        "!!!Metadata (Do not modify)!!!": {
            "Major Version A": 3,
            "Major Version B": 0,
            "Minor Version A": 1,
            "Minor Version B": 0
        },
        "Ingame Resolutions": [
            "640x480",
            "800x600",
            "1024x720",
            "1280x720",
            "1360x720"
        ],
        "Ingame Resolution Mode": 3,
        "Main Menu Resolution": "800x600",
        "Custom MPQ File": "d2dx_sgd2freeres.mpq",
        "Enable Screen Border Frame?": true,
        "Use Original Screen Border Frame?": true,
        "Use 800 Interface Bar?": false
    },
    "!!!Globals!!!": {
        "Config Tab Width": 4
    }
}

```
![1](https://user-images.githubusercontent.com/33173384/118011074-31597a00-b382-11eb-94c2-5b5ad38201f6.png)
![11](https://user-images.githubusercontent.com/33173384/118011126-4209f000-b382-11eb-9916-33165a5f75e0.png)
![12](https://user-images.githubusercontent.com/33173384/118011136-433b1d00-b382-11eb-991e-a5d3f7444742.png)
![13](https://user-images.githubusercontent.com/33173384/118011140-43d3b380-b382-11eb-9047-09b707fb6815.png)
![14](https://user-images.githubusercontent.com/33173384/118011147-4504e080-b382-11eb-88cf-bb76f1bf4cf4.png)
![15](https://user-images.githubusercontent.com/33173384/118011151-46360d80-b382-11eb-840c-be46bcdf246f.png)

**Comment by bolrog** [comment]
Regarding D2DX_SGD2FreeRes.json, it's written every time you start D2DX (default settings with built-in res mod), and this is intentional. Please use d2dx.cfg to control resolution in this scenario.

The other scenario is "standalone" sgd2freeres, then you should give -dxnoresmod instead, and d2dx won't get in the way.

**Comment by bolrog** [comment]
"AV detecting glide3x.dll as a virus (maybe signature)"

This might be because I unpack and drop a dll in the folder (sgd2freeres). Hm..

**Comment by MAXBURAOT** [comment]
Diablo v1.14d is wow widescreen is working hehehe
-Can set only 3 Display modes
-so if i set something in D2DX.cfg display size like ex size=[1360,720], it will be the last display on diablo II UI, previous version of d2dx i can set a lot of display settings in SGD2FreeResolution.json and its working

```
My SGD2FreeResolution.json Settings
{
    "SlashGaming Diablo II Free Resolution": {
        "!!!Metadata (Do not modify)!!!": {
            "Major Version A": 3,
            "Major Version B": 0,
            "Minor Version A": 1,
            "Minor Version B": 0
        },
        "Ingame Resolutions": [
            "640x480",
            "800x600",
            "1024x720",
            "1280x720",
            "1360x720"
        ],
        "Ingame Resolution Mode": 3,
        "Main Menu Resolution": "800x600",
        "Custom MPQ File": "SGD2FreeRes.mpq",
        "Enable Screen Border Frame?": true,
        "Use Original Screen Border Frame?": true,
        "Use 800 Interface Bar?": false
    },
    "!!!Globals!!!": {
        "Config Tab Width": 4
    }
}
```

![1](https://user-images.githubusercontent.com/33173384/118013934-3e2b9d00-b385-11eb-8689-9491da2fa857.png)
![2](https://user-images.githubusercontent.com/33173384/118013937-3f5cca00-b385-11eb-8c48-051434fddf1d.png)
![3](https://user-images.githubusercontent.com/33173384/118014268-982c6280-b385-11eb-83dd-cd2d0bd7f9a3.png)

**Comment by bolrog** [comment]
Glad you got it working! Closing this for now.
