### ISSUE TITLE
Graphical Bug

### ISSUE THREAD

**Issue by iamyoyz** [bolrog/d2dx#6]
Greetings I would like to first thank you for your effort on doing this wrapper anyway this is the bug I found on your latest build the first image is that box on the upper right corner and the 2nd one is when I talk to the npc some of the text are messed up when it reaches at the top of the screen for your info just check the images thank you and hopefully it will be fix soon.. by the way this is the setting I used

-3dfx -gx1080  -gxskiplogo

and I havn't installed pluggy and other mods yet by the way all I did was doing fresh install of 1.14d client and test this wrapper :D 

hope you could fix it soon :D 

![bug1](https://user-images.githubusercontent.com/74028788/111995007-69e39100-8b53-11eb-8363-74881dd1a646.jpg)
![Bug2](https://user-images.githubusercontent.com/74028788/111995017-6bad5480-8b53-11eb-85de-ff416c0c6f39.jpg)

**Comment by bolrog** [comment]
This should be fixed in 0.9.210323.

**Comment by bolrog** [comment]
Btw the text being squashed in -gx1080 still happens. I would recommend using normal fullscreen mode (looks surprisingly good) until I fix this.

**Comment by iamyoyz** [comment]
its ok :D just do it 1 at a time at least it fixed the first one

**Comment by bolrog** [comment]
If you use 1.13d (or 1.13c or 1.12) you should be able to run the game in widescreen now, without squished text issues, in the latest version.
