### ISSUE TITLE
0.99.511 Bugs

### ISSUE THREAD

**Issue by fapmilk** [bolrog/d2dx#60]
1. Automap cross / X icon for npcs and players is distorted.

[town d2dx-0.99.510](https://i.imgur.com/a3zpqq1.jpg)
[town d2dx-0.99.511](https://i.imgur.com/eTBILJd.jpg)
[stony d2dx-0.99.510](https://i.imgur.com/5Ql7aY8.jpg)
[stony d2dx-0.99.511](https://i.imgur.com/N7zHmYp.jpg)

2. Selecting low Lighting Quality turns all terrain and some objects completely black.

[Low Lighting](https://i.imgur.com/MvBReCI.jpg)

3. Enabling Perspective turns many objects invisible.

[Perspective On](https://i.imgur.com/f0MUv0b.jpg)

I only tested on 1.13d. These issues occur even at 640x480 and 800x600 with testmop=false, noresmod=true, nowide=true.

Another issue I found, that may not be relevant now, is that clicking the Automap options while in game frequently causes a crash in the previous release 0.99.510. It's fine to change the options in the registry, or even in game with the various automap keybinds, but as soon as I click through the options in the ESC menu it causes a crash within 1-3 clicks. It doesn't occur with d3d or ddraw.

**Comment by Pear1st** [comment]
![image](https://user-images.githubusercontent.com/78216520/117900634-26f49d00-b2fc-11eb-87b7-fac723bfc58f.png)
my issues occur in the red box

**Comment by iamyoyz** [comment]
> ![image](https://user-images.githubusercontent.com/78216520/117900634-26f49d00-b2fc-11eb-87b7-fac723bfc58f.png)
> my issues occur in the red box and the buildings are missing！

maybe the resolution is too big? since the game created was 800x600?

**Comment by fapmilk** [comment]
Yes I don't believe that's anything to do with D2DX. It's just the way the game was designed, for performance reasons I assume. As you increase resolution you'll see more empty / black terrain at the edges and things like trees and lights will start disappearing.

**Comment by Pear1st** [comment]
> > ![image](https://user-images.githubusercontent.com/78216520/117900634-26f49d00-b2fc-11eb-87b7-fac723bfc58f.png)
> > my issues occur in the red box and the buildings are missing！
> 
> maybe the resolution is too big? since the game created was 800x600?

1280x720，maybe that is it

**Comment by tytannial** [comment]
In original game, only 1300x700 map will be rendered.

**Comment by Pear1st** [comment]
> In original game, only 1300x700 map will be rendered.

What about the missing buildings? 1300x700 fix the black render issues, but the buildings are still roof-only...

**Comment by bolrog** [comment]
I can confirm that Perspective mode is broken.
So is low quality lighting mode.

Sorry, I'll update with a fix as soon as I can.

**Comment by Yh793** [comment]
Latest release is fix,thank bolrog.
![image](https://user-images.githubusercontent.com/69706356/117975385-35c16b00-b361-11eb-8095-194d42558910.png)
