### ISSUE TITLE
Borderless window mode

### ISSUE THREAD

**Issue by iamyoyz** [bolrog/d2dx#61]
this is just a suggestion maybe its possible for you to put an option for borderless window mode? 😎

**Comment by bolrog** [comment]
So basically windowed mode without borders, just the game image showing?

**Comment by iamyoyz** [comment]
> So basically windowed mode without borders, just the game image showing?

yes sir 😎

**Comment by bolrog** [comment]
There's a new "frameless" option in the config file in 0.99.512c, should do what you're after.

**Comment by updawg** [comment]
Bolrog,

You are a machine! Thanks for the constant updates.

**Comment by iamyoyz** [comment]
thanks for implementing  cheers! 😎
