### ISSUE TITLE
[bug] cursor stick on left edge when fullscreen on customized res

### ISSUE THREAD

**Issue by CaiMiao** [bolrog/d2dx#62]
tested with 1068x600, clip cursor is on.

can't not move out cursor from the edge.

![image](https://user-images.githubusercontent.com/4640483/117980101-90ad8f00-b36e-11eb-8c97-c7cc3550463a.png)

**Comment by bolrog** [comment]
Multi-monitor?

**Comment by CaiMiao** [comment]
single mon laptop.

![image](https://user-images.githubusercontent.com/4640483/117980979-7cb65d00-b36f-11eb-8b0d-159b55e1592c.png)

**Comment by iamyoyz** [comment]
> tested with 1068x600, clip cursor is on.
> 
> can't not move out cursor from the edge.
> 
> ![image](https://user-images.githubusercontent.com/4640483/117980101-90ad8f00-b36e-11eb-8c97-c7cc3550463a.png)
> 

I've encountered this problem.. Just set it to 1024x600 and it fixes the problem

**Comment by bolrog** [comment]
I've found a bug that causes this, will fix.

**Comment by bolrog** [comment]
Fixed in 0.99.512b
