### ISSUE TITLE
Wrapper won't work multiplayer since 0.99.511

### ISSUE THREAD

**Issue by 0x4e44** [bolrog/d2dx#64]
The best resolution we can get in multiplayer game right now is only 800x600. The wrapper seems to work only in single player since the version : 0.99.511

0.99.512c - not working 
0.99.511   - not working 
0.99.510   - working. 

Working great in single player although resolution is quite odd and don't look too good.

**Comment by bolrog** [comment]
Hmm. Regular bnet?

**Comment by iamyoyz** [comment]
> The best resolution we can get in multiplayer game right now is only 800x600. The wrapper seems to work only in single player since the version : 0.99.511
> 
> 0.99.512c - not working 
> 0.99.511   - not working 
> 0.99.510   - working. 
> 
> Working great in single player although resolution is quite odd and don't look too good. 

Im not sure if its allowed in battle.net it might get your account banned

**Comment by 0x4e44** [comment]
Private server. Yeah on B.Net you might get banned. But although it is okay if it is not working anymore with the newest HDMOD pack that is included. Although I was wondering what is so different between have the gliderunning on Multiplayer versus single player on a server perspective. Also Running the default glide from sven is okay and approved by Blizzard.

**Comment by bolrog** [comment]
Hmm for private servers it's more a case of what's allowed by the admins. I am not sure how to approach this, but it's true the SGD2FreeRes bundled with D2DX has a multiplayer whitelist, which does restrict more than release 510 did.

**Comment by MAXBURAOT** [comment]
Game crash when creating multiplayer/hosting a game using v0.99.512c
I test in v.1.13d and v1.14d

![11](https://user-images.githubusercontent.com/33173384/118127668-95387d00-b42c-11eb-9e51-7c3c2f60c9dc.png)
![111](https://user-images.githubusercontent.com/33173384/118127672-95d11380-b42c-11eb-83de-043088f17248.png)


[Crash.txt](https://github.com/bolrog/d2dx/files/6472464/Crash.txt)
[Crash1.txt](https://github.com/bolrog/d2dx/files/6472466/Crash1.txt)
[Crash2.txt](https://github.com/bolrog/d2dx/files/6472469/Crash2.txt)

**Comment by bolrog** [comment]
Thanks, I'll investigate

**Comment by bolrog** [comment]
Found the issue causing the crash when trying to host a network game. Fix will be included in the next release.

**Comment by MAXBURAOT** [comment]
Nice its working now in multiplayer D2 v1.14d

![2](https://user-images.githubusercontent.com/33173384/118405361-2e27fc00-b6aa-11eb-9f30-3e0913616311.png)
![1](https://user-images.githubusercontent.com/33173384/118405363-2f592900-b6aa-11eb-87da-461103352e41.png)

**Comment by bolrog** [comment]
Published in release 516. Thanks for testing!

**Comment by 0x4e44** [comment]
I did test out the build , same issue when going on B.Net (on my private server) 

There is not a single restriction on my end, so there must be something just like plugy that disable de B.Net Functionnality. The old wrapper still works just to make sure that the server side is not doing any restriction.

Also tested on 1.13c and 1.14D , same issue.

**Comment by MAXBURAOT** [comment]
> I did test out the build , same issue when going on B.Net (on my private server)
> 
> There is not a single restriction on my end, so there must be something just like plugy that disable de B.Net Functionnality. The old wrapper still works just to make sure that the server side is not doing any restriction.
> 
> Also tested on 1.13c and 1.14D , same issue.

Maybe this in PlugY.ini lol

```
[GENERAL]
DisableBattleNet=1
```

**Comment by bolrog** [comment]
Closing because I'm not sure if there are any remaining issues. Feel free to reopen if needed.
