### ISSUE TITLE
-dxscale beyond the boundary

### ISSUE THREAD

**Issue by Yh793** [bolrog/d2dx#65]
Mr,bolrog.

The window is always out of bounds using the -dxscale. I saw on WIKI that D2DX adjusts automatically. this feature not work? thanks.
`desktop resolution 1920x1080`
`game version 1.13c`
my cfg https://pastebin.com/iBBuP4K2
![TTT](https://user-images.githubusercontent.com/69706356/118107596-87c1c980-b411-11eb-9ea2-dc7dedec474d.png)

**Comment by iamyoyz** [comment]
this also happens in 1.14d client

**Comment by sv-v5** [comment]
Looking at the config
```
[game]
size=[720,540]			# if [-1,-1] d2dx will decide a suitable game size, otherwise will use the size given here
```

does setting `size=[-1,-1]` get a window that's scaled to fit the screen?

I think the default is like that 
```
[game]
size=[-1,-1]		# if [-1,-1]
```
https://github.com/bolrog/d2dx/wiki/Configuration-File

**Comment by bolrog** [comment]
If you give size=[-1,-1], D2DX will pick a resolution from this table: https://github.com/bolrog/d2dx/wiki/In-game-Resolutions

**Comment by Yh793** [comment]
sorry,my english is bad.
windowed/fullscreen default `size=[-1,-1]` works well with `-dxscale1`,default `size=[-1,-1]` windowed size `960x540`.fullscreen size `1920x1080`.

window mode uses `size=[-1,-1]` or `other size` with  `-dxscale2` Will exceed the work space.
see WIKI workspace define.

Specifying one of these options will scale the window by a factor of 2 or 3 respectively in windowed mode. If there isn't sufficient room (`between the top of the taskbar and the top of the screen`) the scale factor will be lowered.

fullscreen mode can limit the game screen to 1980x1080.
`-dxscale1 -dxscale2 -dxscale3` 
`size=[-1,-1]  size=[720,540] ` All can run well.
window mode game screen alway larger than the workspace.

**Comment by bolrog** [comment]
I understand, I'll fix this.

**Comment by bolrog** [comment]
Should be fixed in release 518, let me know if it's ok!

**Comment by Yh793** [comment]
thanks,Mr.bolrog.
i tested `640x480 800x600 [-1,-1] 1280x720`,release 518 fix that .
see Screenshot, Half of the window title exceeds the top,If this is an integer scaling mechanism, 
Please close the question.Thank you again.

![tt2](https://user-images.githubusercontent.com/69706356/118632860-6f7fef00-b803-11eb-9380-045a1995d9e2.png)

**Comment by bolrog** [comment]
My bad... should be fixed in 518b now.

**Comment by Yh793** [comment]
> My bad... should be fixed in 518b now.

thanks,Mr.bolrog
new screenshot with 518b
![image](https://user-images.githubusercontent.com/69706356/118647022-77e02600-b813-11eb-80b1-40fda8665374.png)
