### ISSUE TITLE
Plugy not working

### ISSUE THREAD

**Issue by XPZ2k15** [bolrog/d2dx#67]
When launching Plugy w/ Diablo

I get the error below. If I start diablo without plugy it works just fine.

![image](https://user-images.githubusercontent.com/38363692/118408905-9d670700-b63c-11eb-9c45-d94d76b3ee27.png)

**Comment by bolrog** [comment]
You probably have a standalone version of SGD2FreeRes in your folder. If you remove it, D2DX will use it's built-in one instead.

Or upgrade your standalone SGD2FreeRes (the latest supports D2DX) and start with -dxnoresmod to use the standalone one.

**Comment by XPZ2k15** [comment]
I have deleted all SGD2FreeRes files in my diablo folder(s) including in the plugy folder as well ( These are files that D2DX generate on it's own ). I don't have any standalone SGD2FreeRes installed. Is there a discord by the way? Still nothing after deleting those files.


![image](https://user-images.githubusercontent.com/38363692/118409086-a1475900-b63d-11eb-8bf3-e64885509456.png)

**Comment by bolrog** [comment]
Weird. Which PlugY version is it btw?

**Comment by XPZ2k15** [comment]
Plugy 14.01

**Comment by admonished** [comment]
same problem here. d2dx 0.99.510 is the latest version that works for me

**Comment by bolrog** [comment]
Very odd. I have PlugY myself. Could you attach your plugy config file?
I'm also curious why the sgd2freeres files would land in the PlugY subfolder.. they don't for me. I just launch the game by running PlugY.exe from the D2 folder.

**Comment by MAXBURAOT** [comment]
> When launching Plugy w/ Diablo
> 
> I get the error below. If I start diablo without plugy it works just fine.
> 
> ![image](https://user-images.githubusercontent.com/38363692/118408905-9d670700-b63c-11eb-9c45-d94d76b3ee27.png)

**Solution for this, you will encounter this error if you put the glide3x.dll inside Diablo II root folder, you need to copy the glide3x.dll inside the Plugy folder**

For reference ive post this error also
https://github.com/bolrog/d2dx/issues/57

@XPZ2k15 
Plugy is working fine for me dude using diablo v1.14d
tested with nGlide and D2DX v0.99.516
![1](https://user-images.githubusercontent.com/33173384/118481994-bbb92980-b746-11eb-8657-b580a1fcd261.png)
![2](https://user-images.githubusercontent.com/33173384/118482003-bd82ed00-b746-11eb-8389-92be1b876d56.png)
![3](https://user-images.githubusercontent.com/33173384/118482007-bfe54700-b746-11eb-8d39-994fd11b485e.png)

![4](https://user-images.githubusercontent.com/33173384/118482548-7517ff00-b747-11eb-9c9b-8fdbaf1dc80b.png)
![5](https://user-images.githubusercontent.com/33173384/118482552-76e1c280-b747-11eb-8a00-26ff452c2814.png)
![6](https://user-images.githubusercontent.com/33173384/118482558-79441c80-b747-11eb-9503-aba5b5252104.png)

**Comment by bolrog** [comment]
It seems that PlugY can be installed in multiple ways. The way I've done it personally is to copy PlugY.exe etc into the D2 folder. (The PlugY subfolder just contains the data files, no executables.) This has worked fine at least.

**Comment by MAXBURAOT** [comment]
for reference heres my folder structure for Plugy v14.02

![11](https://user-images.githubusercontent.com/33173384/118493140-5c154b00-b753-11eb-9a50-917b4fa47913.png)

**Comment by XPZ2k15** [comment]
@MAXBURAOT copying the glide dll to the plugy folder indeed fixed this. Closing this issue.

Thank you!
