### ISSUE TITLE
build 0.99.516 fps becomes unstable after a few seconds loading the character from high 60 to choppy and glitchy

### ISSUE THREAD

**Issue by cedricwaltercson** [bolrog/d2dx#69]
build 0.99.516 fps becomes unstable after a few seconds loading the character from high 60 to choppy and glitchy

**Comment by cedricwaltercson** [comment]
Game version: 1.0.13.64 (supported)

Apparent Windows version: 10.0 (build 19042).
Actual Windows version: 10.0 (build 0).
Suggesting game size 960x540.
Writing SGD2FreeRes files.
Initializing SGD2FreeRes.
Fps fix aborted: location appears to be patched already.
Using 'Interval1' sync strategy.
Using 'FlipDiscard' swap strategy.
Created device supports D3D_FEATURE_LEVEL_11_1.
Using 'ResizeBuffers' backbuffer sizing strategy.
Device context supports ID3D11DeviceContext1. Will use this to discard resources and views.
Setting maximum frame latency to 1.
Sizes: desktop 1920x1080, window 800x600, game 640x480, render 1440x1080
The device supports 2048 textures per atlas.
Total size of texture caches is 240256 kB.
Using DXGI_FORMAT_R10G10B10A2_UNORM for the render buffer.
Feature flags:
  UnitMotionPrediction
  WeatherMotionPrediction
  TextMotionPrediction
Sizes: desktop 1920x1080, window 800x600, game 800x600, render 1440x1080
Sizes: desktop 1920x1080, window 800x600, game 640x480, render 1440x1080
Sizes: desktop 1920x1080, window 800x600, game 800x600, render 1440x1080
Sizes: desktop 1920x1080, window 960x540, game 960x540, render 1920x1080
Sizes: desktop 1920x1080, window 800x600, game 640x480, render 1440x1080
Sizes: desktop 1920x1080, window 800x600, game 800x600, render 1440x1080
Sizes: desktop 1920x1080, window 960x540, game 960x540, render 1920x1080
Sizes: desktop 1920x1080, window 800x600, game 800x600, render 1440x1080

I hope the log helps..

**Comment by bolrog** [comment]
Hi, it looks like you're using some mod or a non-vanilla game, do you know which mod or what you might have installed?

**Comment by cedricwaltercson** [comment]
I'll run a fresh install and report back in a bit..

**Comment by cedricwaltercson** [comment]
but basically the only thing that was running was plugy with basemod

**Comment by bolrog** [comment]
It might be related to BaseMod and possibly the "CPU fix" that it has. I'll try to run that later today and see if I can reproduce the issue. If you want to, try disabling the CPU fix in basemod and see if that helps.

**Comment by cedricwaltercson** [comment]
PlugY works and no issues..
I have basemod, bh, SGD2FreeRes, pd2-cnc-ddraw

**Comment by cedricwaltercson** [comment]
I'll see if I can reproduce it on basemod only but all of them installed becomes choppy and rubberbands as if it was an actual server..

**Comment by cedricwaltercson** [comment]
I just confirmed yeah looks like it happens with basemod installed..

**Comment by bolrog** [comment]
My suspicion seems to have been confirmed then. :) It is likely due to the CPU fix in basemod assuming the game will run at 25 fps.

**Comment by iamyoyz** [comment]
what client are you using I also have base mod installed and I use 1.14d client and I dont have problems like this one you are experiencing

**Comment by cedricwaltercson** [comment]
I'm on 1.13D. I've disabled the bypassfps in basemod config and seems the issue has gone away.. its pretty cool combining it with SlashBH's fps patch runs as if its meant to be

**Comment by bolrog** [comment]
I've added a Compatibility section to the Wiki, describing this fix.

**Comment by iamyoyz** [comment]
or try updating your client to 1.14d I dont have problems like this 
![bug1](https://user-images.githubusercontent.com/74028788/118476929-b5c04a00-b740-11eb-8682-e2027e4d9207.jpg)
![Bug2](https://user-images.githubusercontent.com/74028788/118476959-be188500-b740-11eb-8cfd-c388cc7b5245.jpg)
