### ISSUE TITLE
D2DX prevented multi instance in some circumstance

### ISSUE THREAD

**Issue by CaiMiao** [bolrog/d2dx#70]
maybe #58 wanted to decribe this problem but failed due to broken english.

tested with Median XL Sigma, can't open 2 game instance with D2DX but can open another without D2DX (GDI/DDraw/D3D).

also you can open another instance using D2DX with game from another location.

you can just try open 2 instance with any version with plugy.exe (from plugy), it won't load second one.

**Comment by bolrog** [comment]
I wonder if SGD2FreeRes might be blocking this. Does -dxnoresmod help?

**Comment by Yh793** [comment]
> I wonder if SGD2FreeRes might be blocking this. Does -dxnoresmod help?

`-dxnoresmod ` not work
`-dxnoresmod ` and `SlashGaming-Diablo-II-Free-Multibox` not work
game version 1.13c

**Comment by MAXBURAOT** [comment]
> I wonder if SGD2FreeRes might be blocking this. Does -dxnoresmod help?

yah confirmed ive test it even thou i have a hexed D2 v1.14d enabled multi window when using D2DX the 2nd window doesnt work, ive set also -dxnoresmod to true and false and still the same.

DIablo 2 v.1.14d Hexed exe using -w parameters only
![4444](https://user-images.githubusercontent.com/33173384/118487984-da6eee80-b74d-11eb-85da-0b415da4c1ea.png)

**Comment by bolrog** [comment]
I just tried this on 1.13d by manually doing a multibox patch. I could launch two instances of build 518b this way. Hmm.

**Comment by CaiMiao** [comment]
checked with latest version, it works indeed. thank you!
