### ISSUE TITLE
Feature Request: Main Menu Resolution and Shader support that of cnc-ddraw

### ISSUE THREAD

**Issue by cedricwaltercson** [bolrog/d2dx#73]
Can you please add Main Menu Resolution 800x600 to stretch or an option to opt in and out of maintaining aspect ratio?
Might be too much to ask.. but are you willing to include shader support that of cnc-draw and the various shaders available or at least the compatibility with cnc-ddraw?

**Comment by iamyoyz** [comment]
I've been asking funkyfresh already about adding support for v1.14d version but I guess he won't do it because he is concern that it will be used on battle.net and gets the account banned... So If you are using the old version I think it will work..

**Comment by cedricwaltercson** [comment]
I'm unsure of how maintaining aspect ratio option in the config that would allow the main menu to stretch in the resolution of 800×600 be bannable..nor the shader support.. its merely cosmetic..

**Comment by MAXBURAOT** [comment]
Shaders on Glide not sure about that, main menu strech maybe, same like nGlide stretch main menu

**Comment by bolrog** [comment]
You can use ReShade to add shaders, I don't want to build that into D2DX because it would quickly look like a mess.

I am thinking of ways to make the main menu prettier in widescreen modes, it won't be stretching but I'll hopefully come up with something.

**Comment by cedricwaltercson** [comment]
Also please don't forget to enable 60+ FPS to main menu :)

**Comment by cedricwaltercson** [comment]
@bolrog  build 0.99.519 has Unlock FPS Menu.. However I haven't noticed any difference and cursor is still choppy on main menu compared to in-game.. Also the sleepfix seems to improve some stutter and feels somewhat more fluid.

**Comment by bolrog** [comment]
Strange. It should be enabled by default for 1.13D. Could you post the d2dx.log?

**Comment by cedricwaltercson** [comment]
Game version: 1.0.13.64 (supported)

Apparent Windows version: 10.0 (build 19042).
Actual Windows version: 10.0 (build 0).
Suggesting game size 1068x600.
Writing SGD2FreeRes files.
Initializing SGD2FreeRes.
Menu fps fix applied.
Fps fix applied.
In-game sleep fixes applied.
Using 'FlipDiscard' swap strategy.
Using 'Interval1' sync strategy.
Created device supports D3D_FEATURE_LEVEL_11_1.
Using 'ResizeBuffers' backbuffer sizing strategy.
Device context supports ID3D11DeviceContext1. Will use this to discard resources and views.
Setting maximum frame latency to 1.
Sizes: desktop 1920x1080, window 800x600, game 640x480, render 1440x1080
The device supports 2048 textures per atlas.
Total size of texture caches is 240256 kB.
Using DXGI_FORMAT_R10G10B10A2_UNORM for the render buffer.
Feature flags:
  UnitMotionPrediction
  WeatherMotionPrediction
  TextMotionPrediction
Sizes: desktop 1920x1080, window 800x600, game 800x600, render 1440x1080
Sizes: desktop 1920x1080, window 800x600, game 640x480, render 1440x1080
Sizes: desktop 1920x1080, window 800x600, game 800x600, render 1440x1080

**Comment by bolrog** [comment]
By "Menu fps fix applied." it should have worked. What other mods are you using?

**Comment by cedricwaltercson** [comment]
@bolrog PlugY, Basemod, SlashBH
I'll test on a clean no mods

**Comment by cedricwaltercson** [comment]
@bolrog it works on vanilla clean lod 1.13d
I'll test on which mod it stops working

**Comment by cedricwaltercson** [comment]
@bolrog culprit is basemod again.. lol
but don't know what option needs to be off for it to work..

**Comment by cedricwaltercson** [comment]
it's odd as the in-game is fine but main menu high fps for some reason gets disabled when basemod plugin is loaded

**Comment by bolrog** [comment]
I see! Actually that might explain it, because many of the "CPU fixes" included in D2 mods work against the high-fps feature in D2DX by adding more "sleep" calls. 

The "sleep fix" that I'm working on and that is in release 519 will eventually sort this out. Looks like you found a new case I hadn't seen before, so I'll investigate this. Thanks!

**Comment by bolrog** [comment]
It should be fixed now in release 521. Also adjusted the patches for basemod so that BypassFPS can be 1 without getting stuttering.

**Comment by cedricwaltercson** [comment]
I'll test when I can and confirm..

**Comment by cedricwaltercson** [comment]
@bolrog It works flawlessly! even with the BypassFPS enabled by default in Basemod.

**Comment by bolrog** [comment]
Good to hear!

**Comment by bolrog** [comment]
I'll close this issue and create one for the original case i want to address - main menu aspect ratio.
