### ISSUE TITLE
Critical Error on 1.14d after updating glider to 0.99.518b

### ISSUE THREAD

**Issue by iamyoyz** [bolrog/d2dx#75]
Greetings I have experience this when I launch the game

![newbug1](https://user-images.githubusercontent.com/74028788/118796985-b38bf600-b8ce-11eb-92ff-7c8776d09bc7.jpg)

[Crash.txt](https://github.com/bolrog/d2dx/files/6507867/Crash.txt)
[D2210519.txt](https://github.com/bolrog/d2dx/files/6507868/D2210519.txt)

here are the log files on the crash from the game

**Comment by bolrog** [comment]
It looks like you're using BaseMod, what settings are you using?

**Comment by iamyoyz** [comment]
> 
> 
> It looks like you're using BaseMod, what settings are you using?

yeah I am  hehehe here is the basemod config file 
[config.txt](https://github.com/bolrog/d2dx/files/6508728/config.txt)

**Comment by bolrog** [comment]
It's not crashing for me, for some reason. What about the D2DX cfg or cmdline options?

**Comment by iamyoyz** [comment]
> 
> 
> It's not crashing for me, for some reason. What about the D2DX cfg or cmdline options?

here is the d2dx cfg I use

[d2.txt](https://github.com/bolrog/d2dx/files/6509356/d2.txt)

**Comment by bolrog** [comment]
The strange thing is, it crashed *once* for me with the same error you got...

**Comment by iamyoyz** [comment]
> 
> 
> The strange thing is, it crashed _once_ for me with the same error you got...

well I don't know what happened but I did a test I roll back to 0.99.517 and it runs perfectly then re copy all the files from 0.99.518b and now runs pefectly without crash... So Hopefully it won't have an error like this again
