### ISSUE TITLE
519 release d2dx.cfg doesn't work.

### ISSUE THREAD

**Issue by Yh793** [bolrog/d2dx#77]
Mr.bolrog
519 release config file doesn't work.

Command-line be OK.

**Comment by bolrog** [comment]
Just tried it, and it works for me. Do you have the d2dx.cfg file open in some other app? Or maybe there's a game.exe stuck in the task manager?

**Comment by Yh793** [comment]
> Just tried it, and it works for me. Do you have the d2dx.cfg file open in some other app? Or maybe there's a game.exe stuck in the task manager?
Thank you. I returned to normal after reinstalling and restarting my computer.
