### ISSUE TITLE
Document installation steps for isolated Plugy

### ISSUE THREAD

**Issue by TheDuriel** [bolrog/d2dx#80]
Game Version: 1.14d - Blizzard Download

Plugy Version: 14.02

D2DX Version: 0.99.521

`"D:\Games\Diablo II\Diablo II.exe" -3dfx -w` Succeeds in launching the game with D2DX

`"D:\Games\Diablo II\Mod PlugY\PlugY.exe" -3dfx` Fails to launch with the following error:

![image](https://user-images.githubusercontent.com/44248915/119366927-c0835d80-bcb1-11eb-87d9-0d240624344e.png)

Log file contents:

```
Game version: 1.14.3.71 (supported)

Apparent Windows version: 10.0 (build 19042).
Actual Windows version: 10.0 (build 0).
Writing SGD2FreeRes files.
Suggesting game size 960x540.
Initializing SGD2FreeRes.
```

Solution:

Copy glide3x.dll and d2dx-defaults.cfg into the plugy subdirectory.

^Would be wonderful if this could be documented in the wiki.

**Comment by iamyoyz** [comment]
or you could use the zip version of plugy and patch the game.exe(using gamepatcher) so you wont use plugy.exe to launch the game

**Comment by bolrog** [comment]
Added it here: https://github.com/bolrog/d2dx/wiki/Compatibility-with-other-mods

Let me know if it looks ok! I left out the d2dx-defaults.cfg part, because that shouldn't be necessary (and D2DX will only read the file if it's named "d2dx.cfg" anyway).

**Comment by TheDuriel** [comment]
Looks good.
