### ISSUE TITLE
ProjectD2 doesn't work with multiplayer

### ISSUE THREAD

**Issue by Krillien** [bolrog/d2dx#81]
I'm getting an error saying 'wrong game version' whenever I create a game in the PD2 realm. It seems like PD2 requires a specific version of D2HD.dll, any any other version will trigger the error above.

Single player works fine however.

Is this something that can be fixed?

**Comment by bolrog** [comment]
Hm, not on my end. I think the PD2 guys need to whitelist D2DX somehow then.

**Comment by Krillien** [comment]
Noted. I've opened a ticket with the PD2 team, if I get any updates I'll update this issue.

**Comment by MAXBURAOT** [comment]
![2](https://user-images.githubusercontent.com/33173384/119682893-d3df2600-be75-11eb-9619-d6004e0008f1.png)

![Uploading 3.png…]()

**Comment by MAXBURAOT** [comment]
Hmm just testing ony PD2, only 2 modes of  display only still figuring how to make it widescreen Single/Multi seems  ok  :)

![2](https://user-images.githubusercontent.com/33173384/119684687-47cdfe00-be77-11eb-8cfd-8a9a1f447296.png)
![3](https://user-images.githubusercontent.com/33173384/119685329-d93d7000-be77-11eb-9483-ed534f552e75.png)
![4](https://user-images.githubusercontent.com/33173384/119685693-2b7e9100-be78-11eb-9dd6-470aa939c34e.png)

**Comment by Krillien** [comment]
Ah let me clarify - singleplayer and open bnet (self host) multiplayer games are fine. You have to log into the PD2 realm and create a game there to see the wrong game version error.

**Comment by MAXBURAOT** [comment]
> Ah let me clarify - singleplayer and open bnet (self host) multiplayer games are fine. You have to log into the PD2 realm and create a game there to see the wrong game version error.
> 
> Also, you should be able to change to a widescreen resolution in the default video settings menu in game.

later ill try to update my PD2 and test it :)

**Comment by tytannial** [comment]
> > Ah let me clarify - singleplayer and open bnet (self host) multiplayer games are fine. You have to log into the PD2 realm and create a game there to see the wrong game version error.
> > Also, you should be able to change to a widescreen resolution in the default video settings menu in game.
> 
> later ill try to update my PD2 and test it :) thanks for the info

The SGDFreeRes has a limit for PD2. See the Readme at https://github.com/mir-diablo-ii-tools/SlashGaming-Diablo-II-Free-Resolution

**Comment by bolrog** [comment]
Thanks @tytannial, I will be adding a fix where D2DX selects 1068x600 by default when PD2 is detected. That should at least unblock multiplayer if the user doesn't set a res in the config.

**Comment by tytannial** [comment]
> Thanks @tytannial, I will be adding a fix where D2DX selects 1068x600 by default when PD2 is detected. That should at least unblock multiplayer if the user doesn't set a res in the config.

I think you can make the config "size=[-1,-1]" to "size=[[-1,-1],[-1,-1]]", then you can switch res in game, and save last res which has been used. Then you can translate it to SGDFreeRes config with same behavior that SGDFreeRes used.

**Comment by Krillien** [comment]
My ticket got auto-closed so I'm unsure if there is a path forward with the PD2 devs.

However it seems like the missing D2HD.dll is the culprit for multiplayer failing? Is that dll a part of SGDFreeRes? I've tried quickly altering my resolution in game to 1068x600 before the game kicks me out, thinking that the next game might recognize my correct resolution the next game I create - no dice.

**Comment by tytannial** [comment]
> My ticket got auto-closed so I'm unsure if there is a path forward with the PD2 devs.
> 
> However it seems like the missing D2HD.dll is the culprit for multiplayer failing? Is that dll a part of SGDFreeRes? I've tried quickly altering my resolution in game to 1068x600 before the game kicks me out, thinking that the next game might recognize my correct resolution the next game I create - no dice.

I think you could disable build-in widescreen and use pd2's.

**Comment by Krillien** [comment]
I've configured d2dx.cfg with noresmod=true, and added the D2HD.dll back - however the game now refuses to launch saying Glid3x.dll version not supported, please use latest supported version.

**Comment by tytannial** [comment]
Looks like anti-cheat.....🤣

**Comment by bolrog** [comment]
D2HD is an older mod, also by Mir Drualga, which does a similar job as SGD2FreeRes.

Looks to me like the PD2 team will have to add support for SGD2FreeRes. The D2HD included in PD2 does not recognize D2DX as a known Glide wrapper and refuses to load.

**Comment by Krillien** [comment]
bolrog, I'm not sure how to proceed here as it seems like the PD2 dev team aren't responding. A shame really, as I love what you've done with your glide wrapper.

You can probably close this issue, since there isn't a path forward at the moment.

**Comment by MAXBURAOT** [comment]
Still testing PD2 Season 2

![1](https://user-images.githubusercontent.com/33173384/120348363-b3104800-c32f-11eb-90b7-bf5d482eaaab.png)
![2](https://user-images.githubusercontent.com/33173384/120348365-b4417500-c32f-11eb-8997-439733cec785.png)
![3](https://user-images.githubusercontent.com/33173384/120348353-aee42a80-c32f-11eb-8218-e302de3e36ea.png)
![5](https://user-images.githubusercontent.com/33173384/120348357-b1468480-c32f-11eb-831f-4ff2840630f2.png)
![6](https://user-images.githubusercontent.com/33173384/120348358-b1df1b00-c32f-11eb-8eb2-53cba8c547a6.png)

**Comment by Krillien** [comment]
To be fair - using the launcher is **not** required. I'm currently using Sven's glide wrapper via Game.exe -3dfx and there are no issues there. Obviously if PD2 has an update they need to push, I'll need to use the launcher for the update one time.

**Comment by MAXBURAOT** [comment]
> To be fair - using the launcher is **not** required. I'm currently using Sven's glide wrapper via Game.exe -3dfx and there are no issues there. Obviously if PD2 has an update they need to push, I'll need to use the launcher for the update one time.

sven for sure has no issues coz they already using it and it is recognize by PD2 system i dunno if theres an anti cheat system the game always try to update everytime i replace the glide3x.dll with D2DX :)), i think the solution for this is the PD2 Devs by themselves they nedd to allow D2DX :))

**Comment by bolrog** [comment]
Yeah I think it's up to the PD2 guys. Closing this for now.

**Comment by senpaisomething** [comment]
> 
> 
> My ticket got auto-closed so I'm unsure if there is a path forward with the PD2 devs.
> 
> However it seems like the missing D2HD.dll is the culprit for multiplayer failing? Is that dll a part of SGDFreeRes? I've tried quickly altering my resolution in game to 1068x600 before the game kicks me out, thinking that the next game might recognize my correct resolution - no dice.

I just found out about this, feel free to message me (senpaisomething) directly on the pd2 discord. I'd love to chat a bit more

**Comment by Krillien** [comment]
@bolrog - just wondering if it's worth it to re-open this issue given that senpai has reached out. thanks.
