### ISSUE TITLE
Load Save Game Screen Font Bug

### ISSUE THREAD

**Issue by nelsonmenon** [bolrog/d2dx#82]
![image](https://user-images.githubusercontent.com/84519124/119584789-bb044100-bd9f-11eb-85df-1c8b848e6780.png)

when save & exit game, and create click on single player game

d2dx latest version
d2 1.14d
plugy 14.02

**Comment by fapmilk** [comment]
I haven't seen the problem on the character select screen but I've noticed a few issues that I'm guessing are related to this.

For me the potion belt keybind font is distorted. If my inventory is open the font goes back to normal, but is then distorted again after closing the inventory. Also having certain potion slots empty causes the scrambled font to swap to different slots. The font in the keybinds menu is also broken. When I scroll through the keybinds the font seems to kind of stack up on top of each other.

[Potions](https://i.imgur.com/byJ04Nl.jpg)
[Keybinds](https://i.imgur.com/evUHMo1.jpg)

This bug happens on 0.99.525 but not the previous version 0.99.521.

**Comment by bolrog** [comment]
Curious! I'll see if I can repro.

**Comment by bolrog** [comment]
Sorry about this, should be fixed in release 526 now.

**Comment by nelsonmenon** [comment]
tested, and it's ok now.
glad to help.
is there anything more I can do?
great work by the way
