### ISSUE TITLE
Slashbh menu and texts glitching out with the build 0.99.525

### ISSUE THREAD

**Issue by cedricwaltercson** [bolrog/d2dx#83]
![Animation](https://user-images.githubusercontent.com/1785276/119608897-0ff49580-be3a-11eb-9b31-057ad1e83741.gif)

**Comment by cedricwaltercson** [comment]
Was fine with build 0.99.521 and -dxtestsleepfix

**Comment by bolrog** [comment]
Sorry about this, should be fixed in release 526 now.

**Comment by cedricwaltercson** [comment]
@bolrog it is still persisting even on 526 build..

**Comment by bolrog** [comment]
Ok, I'll check slashBH mod.

**Comment by bolrog** [comment]
Actually, I think I realized the problem - MoP being applied to "normal" texts that shouldn't move.
As a test fix I uploaded release 526b now. Please see if it helps.

**Comment by cedricwaltercson** [comment]
@bolrog 526b fixed it!
