### ISSUE TITLE
Graphical artifacts with VSync turned off

### ISSUE THREAD

**Issue by tomasz1986** [bolrog/d2dx#86]
I have very strange graphical artifacts when trying to play with VSync turned off. For example, there are black borders flashing around the screen, and weather effects like rain seem to be moving together with the character. The character's movement is also very wonky.

Here is a short video showing the issue.

https://youtu.be/QPk8bsW_dN0

This is under Windows 10, and the hardware is AMD Ryzen 4350G with its integrated graphics.

**Comment by bolrog** [comment]
Oops. This happens when the framerate becomes too high. Do you have access to a framerate limiter like RTSS? That should help. But I'll also look into adding an internal limiter soon.

**Comment by updawg** [comment]
Same happened to me even utilizing Nvidia's built in limiter. I set the
limit to 144 and it still messes up weather, the character glides when
stopping, and the jagged black bars on the edges appear.

**Comment by bolrog** [comment]
Ah, damn. I'll look into this...

**Comment by tomasz1986** [comment]
> Oops. This happens when the framerate becomes too high. Do you have access to a framerate limiter like RTSS? That should help. But I'll also look into adding an internal limiter soon.

Actually, the framerate in the video was limited to 60fps with RTSS. You can even see the number in the upper-left corner :wink:.

**Comment by bolrog** [comment]
I just realized I had made a terrible mistake in the code.... Now published release 527b which should fix this issue. :)

**Comment by updawg** [comment]
I won't be able to test it until Sunday. But thank you again for your quick
fixes. I love this project.

**Comment by tomasz1986** [comment]
I have just tested the new release, and I can confirm that the issue has been gone 🙂. I have tested it under v1.14d, which has the FPS limited to 200 internally.
