### ISSUE TITLE
High FPS Issue 1.09d [CACTUS]

### ISSUE THREAD

**Issue by XPZ2k15** [bolrog/d2dx#87]
High FPS Doesn't work with 1.09D

It looks like 1.09d only allows resolution change and NO High FPS?

I'm using CACTUS to launch my diablo instances. 

1.13c works fine w/ res + fps
1.12a High FPS w/ NO RES (Documented in D2DX)
1.09D High Res w/ NO FPS(Not Documented in D2DX)

Is the HIGH FPS / Motion Prediction supposed to work on 1.09d?

![image](https://user-images.githubusercontent.com/38363692/119889467-6e2d8100-beeb-11eb-8c3c-0bb24a54021c.png)

**Comment by XPZ2k15** [comment]
Here is the LOG

Game version: 1.0.9.22 (supported)

Apparent Windows version: 10.0 (build 19042).
Actual Windows version: 10.0 (build 0).
Suggesting game size 1280x720.
Writing SGD2FreeRes files.
Initializing SGD2FreeRes.
Fps fix applied.
Menu fps fix applied.
In-game sleep fixes aborted: unsupported game version.
Using 'Interval1' sync strategy.
Using 'FlipDiscard' swap strategy.
Created device supports D3D_FEATURE_LEVEL_11_1.
Using 'ResizeBuffers' backbuffer sizing strategy.
Device context supports ID3D11DeviceContext1. Will use this to discard resources and views.
Setting maximum frame latency to 1.
Sizes: desktop 1920x1080, window 800x600, game 640x480, render 1440x1080
The device supports 2048 textures per atlas.
Total size of texture caches is 240256 kB.
Using DXGI_FORMAT_R10G10B10A2_UNORM for the render buffer.
Feature flags:
Sizes: desktop 1920x1080, window 800x600, game 800x600, render 1440x1080
Sizes: desktop 1920x1080, window 800x600, game 640x480, render 1440x1080
Sizes: desktop 1920x1080, window 800x600, game 800x600, render 1440x1080

**Comment by bolrog** [comment]
This isn't supported yet. Sorry.. I need to figure out a couple of things in 1.09 to get this to work. But I'll get on it soon.

**Comment by bolrog** [comment]
Units and weather done, missiles and hover texts to go.

**Comment by bolrog** [comment]
Turns out that missiles work, so I made a new release with this support added. Only texts are still a bit shaky.

**Comment by XPZ2k15** [comment]
Thank you! I will test this now
