### ISSUE TITLE
Crashes under Linux/Wine

### ISSUE THREAD

**Issue by brzegorz** [bolrog/d2dx#90]
When trying to run 1.13c with Wine, I get a "Failed to detour Win32 functions" error message.

**Comment by bolrog** [comment]
I haven't been able to test in Wine. Hopefully I can find the time to do that.

**Comment by brzegorz** [comment]
Is there some kind of debug log I could generate and provide to help with that?

**Comment by brzegorz** [comment]
I've tinkered a bit, and for some reason the newest release works under Wine for 1.13c+PlugY

**Comment by bolrog** [comment]
Good to hear! Hmm. Well I would need to improve logging a bit, right now it just says it failed (as you noticed). I'll see if I can add some more fine grained error messages.

But you say it works now, even without PlugY?

**Comment by bolrog** [comment]
Closing for now. Feel free to reopen the issue if it happens again.

**Comment by brzegorz** [comment]
Hi, I meant that it works only with PlugY. Sorry for the delay: )
