### ISSUE TITLE
User-specified resolution in d2dx_sgd2freeres.cfg doesn't work

### ISSUE THREAD

**Issue by borgdin** [bolrog/d2dx#94]
Testing Environment: Win10 + Diablo 2 1.14d.
My desktop resolution is 1920x1080, and in-game resolution is 960x540 by default. 
I've tried to edit and add higher resolution like 1024x768 to d2dx_sgd2freeres.cfg, and then saved the change, 
but in-game resolution remains 960x540. This troubles me for a few days.

**Comment by bolrog** [comment]
Copy d2dx-defaults.cfg to the D2 folder, rename it to d2dx.cfg. Then you can set 'size' in the [game] section.

**Comment by borgdin** [comment]
> Copy d2dx-defaults.cfg to the D2 folder, rename it to d2dx.cfg. Then you can set 'size' in the [game] section.

It works and rocks, thanks a million!
Btw, is there any way to stretch the screen? Command "-nofixaspect" doesn't work.

**Comment by bolrog** [comment]
No, there's no way, but why not set a resolution that fits the screen instead?

**Comment by borgdin** [comment]
> No, there's no way, but why not set a resolution that fits the screen instead?

Well, that's good point. Thanks for your great work and quick reply.

**Comment by bolrog** [comment]
Thank you!
