### ISSUE TITLE
Glide3x.dll Version Not Supported - PlugY + PD2

### ISSUE THREAD

**Issue by SilverSix311** [bolrog/d2dx#98]
So I've been trying to get d2dx to work with my install. I keep getting this error.

![image](https://user-images.githubusercontent.com/8906465/120925810-52bf3480-c6a8-11eb-9b19-872d3ee6cf34.png)

Here's a list of things I've tried thus far:
Added `DllToLoad=SGD2FreeRes.dll` to PlugY.ini
I've added `Glide3x.dll` to `~/Diablo II/`, `~/Diablo II/Project D2/`, and `~/Diablo II/PlugY/`

Not really sure what to do from here.

**Comment by bolrog** [comment]
You need to delete the D2HD.dll file. Unfortunately the PD2 launcher keeps reinstalling this, so you can't start PD2 using the launcher.

**Comment by bolrog** [comment]
Did you try it?

**Comment by Krillien** [comment]
@bolrog - not sure you were able to reach out to senpaisomething regarding compatibility with PD2? (latest updates from the closed issue) this would probably resolve multiple pd2 related issues folks have been submitting. thanks.
